var AllFunctionMapping =[{"keyCode":"Multimedia_Fun_0","functionType":"Multimedia","value":"Media Player","hid":"0x999","translate":"Media Player","code":"Multimedia_Fun_0"},
{"keyCode":"Multimedia_Fun_1","functionType":"Multimedia","value":"Play/Pause","hid":"0x0998","translate":"Play/Pause","code":"Multimedia_Fun_1"},
{"keyCode":"Multimedia_Fun_2","functionType":"Multimedia","value":"Next","hid":"0x0997","translate":"Next","code":"Multimedia_Fun_2"},
{"keyCode":"Multimedia_Fun_3","functionType":"Multimedia","value":"Previous","hid":"0x996","translate":"Previous","code":"Multimedia_Fun_3"},
{"keyCode":"Multimedia_Fun_4","functionType":"Multimedia","value":"Stop","hid":"0x995","translate":"Stop","code":"Multimedia_Fun_4"},
{"keyCode":"Multimedia_Fun_5","functionType":"Multimedia","value":"Mute","hid":"0x994","translate":"Mute","code":"Multimedia_Fun_5"},
{"keyCode":"Multimedia_Fun_6","functionType":"Multimedia","value":"Volume up","hid":"0x993","translate":"Volume up","code":"Multimedia_Fun_6"},
{"keyCode":"Multimedia_Fun_7","functionType":"Multimedia","value":"Volume down","hid":"0x992","translate":"Volume down","code":"Multimedia_Fun_7"},
{"keyCode":"Multimedia_Fun_8","functionType":"Multimedia","value":"Next track","hid":"0x991","translate":"Next trac","code":"Multimedia_Fun_8"},
{"keyCode":"Multimedia_Fun_9","functionType":"Multimedia","value":"Previoustrack","hid":"0x990","translate":"Previoustrack","code":"Multimedia_Fun_9"},
{"keyCode":"KEYBOARD_Fun_10","functionType":"KEYBOARD","value":"Profilecycleup","hid":"0x899","translate":"Profilecycleup","code":"KEYBOARD_Fun_10"},
{"keyCode":"KEYBOARD_Fun_11","functionType":"KEYBOARD","value":"Profilecycledown","hid":"0x898","translate":"Profilecycledown","code":"KEYBOARD_Fun_11"},
{"keyCode":"KEYBOARD_Fun_12","functionType":"KEYBOARD","value":"Layercycleup","hid":"0x897","translate":"Layercycleup","code":"KEYBOARD_Fun_12"},
{"keyCode":"KEYBOARD_Fun_13","functionType":"KEYBOARD","value":"Layercycledown","hid":"0x896","translate":"Layercycledown","code":"KEYBOARD_Fun_13"},
{"keyCode":"MOUSE_Fun_14","functionType":"MOUSE","value":"Leftbutton","hid":"0x895","translate":"Leftbutton","code":"MOUSE_Fun_14"},
{"keyCode":"MOUSE_Fun_15","functionType":"MOUSE","value":"Rightbutton","hid":"0x894","translate":"Rightbutton","code":"MOUSE_Fun_15"},
{"keyCode":"MOUSE_Fun_16","functionType":"MOUSE","value":"Middlebutton","hid":"0x893","translate":"Middlebutton","code":"MOUSE_Fun_16"},
{"keyCode":"MOUSE_Fun_17","functionType":"MOUSE","value":"Forward","hid":"0x892","translate":"Forward","code":"MOUSE_Fun_17"},
{"keyCode":"MOUSE_Fun_18","functionType":"MOUSE","value":"Back","hid":"0x891","translate":"Back","code":"MOUSE_Fun_18"},
{"keyCode":"MOUSE_Fun_19","functionType":"MOUSE","value":"Scrollup","hid":"0x890","translate":"Scrollup","code":"MOUSE_Fun_19"},
{"keyCode":"MOUSE_Fun_20","functionType":"MOUSE","value":"Scrolldown","hid":"0x799","translate":"Scrolldown","code":"MOUSE_Fun_20"},
{"keyCode":"MOUSE_Fun_21","functionType":"MOUSE","value":"Profilecycleup","hid":"0x798","translate":"Profilecycleup","code":"MOUSE_Fun_21"},
{"keyCode":"MOUSE_Fun_22","functionType":"MOUSE","value":"Profilecycledown","hid":"0x797","translate":"Profilecycledown","code":"MOUSE_Fun_22"},
{"keyCode":"MOUSE_Fun_23","functionType":"MOUSE","value":"Batterystatuscheck","hid":"0x796","translate":"Batterystatuscheck","code":"MOUSE_Fun_23"},
{"keyCode":"LaunchProgram","functionType":"LaunchProgram","value":"LaunchProgram","hid":"0x795","translate":"LaunchProgram","code":"LaunchProgram"},
{"keyCode":"LaunchWebsite","functionType":"LaunchProgram","value":"LaunchWebsite","hid":"0x794","translate":"LaunchWebsite","code":"LaunchWebsite"},
{"keyCode":"Shortcuts_Fun_25","functionType":"Shortcuts","value":"Email","hid":"0x793","translate":"Email","code":"Shortcuts_Fun_25"},
{"keyCode":"Shortcuts_Fun_26","functionType":"Shortcuts","value":"Calculator","hid":"0x792","translate":"Calculator","code":"Shortcuts_Fun_26"},
{"keyCode":"Shortcuts_Fun_27","functionType":"Shortcuts","value":"My Computer","hid":"0x791","translate":"My Computer","code":"Shortcuts_Fun_27"},
{"keyCode":"Shortcuts_Fun_28","functionType":"Shortcuts","value":"Explorer","hid":"0x790","translate":"Explorer","code":"Shortcuts_Fun_28"},
{"keyCode":"Shortcuts_Fun_29","functionType":"Shortcuts","value":"WWW Home","hid":"0x789","translate":"WWW Home","code":"Shortcuts_Fun_29"},
{"keyCode":"Shortcuts_Fun_30","functionType":"Shortcuts","value":"WWW Refresh","hid":"0x788","translate":"WWW Refresh","code":"Shortcuts_Fun_30"},
{"keyCode":"Shortcuts_Fun_31","functionType":"Shortcuts","value":"WWW Stop","hid":"0x787","translate":"WWW Stop","code":"Shortcuts_Fun_31"},
{"keyCode":"Shortcuts_Fun_32","functionType":"Shortcuts","value":"WWW Back","hid":"0x786","translate":"WWW Back","code":"Shortcuts_Fun_32"},
{"keyCode":"Shortcuts_Fun_33","functionType":"Shortcuts","value":"WWW Forward","hid":"0x785","translate":"WWW Forward","code":"Shortcuts_Fun_33"},
{"keyCode":"Shortcuts_Fun_34","functionType":"Shortcuts","value":"WWW Search","hid":"0x784","translate":"WWW Search","code":"Shortcuts_Fun_34"},
{"keyCode":"MacroFunction","functionType":"MacroFunction","value":"MacroFunction","hid":"0x783","translate":"MacroFunction","code":"MacroFunction"},
{"keyCode":"ScrollWheel","functionType":"ScrollWheel","value":"ScrollWheel","hid":"0x782","translate":"ScrollWheel","code":"ScrollWheel"},
{"keyCode":"Custom_Fnkey","functionType":"Custom_Fnkey","value":"FN","hid":"0x781","translate":"FN","code":"Custom_Fnkey"},
{"keyCode":"0","functionType":"Singlekey","value":"Left Click","hid":"0x780","translate":"Left Click","code":"Left Click"},
{"keyCode":"1","functionType":"Singlekey","value":"Scroll Click","hid":"0x779","translate":"Scroll Click","code":"Scroll Click"},
{"keyCode":"2","functionType":"Singlekey","value":"Right Click","hid":"0x778","translate":"Right Click","code":"Right Click"},
{"keyCode":"3","functionType":"Singlekey","value":"Back","hid":"0x777","translate":"Back","code":"Back"},
{"keyCode":"4","functionType":"Singlekey","value":"Forward","hid":"0x776","translate":"Forward","code":"Forward"},
{"keyCode":"65","functionType":"Singlekey","value":"A","hid":"0x4","translate":"A","code":"KeyA"},
{"keyCode":"66","functionType":"Singlekey","value":"B","hid":"0x5","translate":"B","code":"KeyB"},
{"keyCode":"67","functionType":"Singlekey","value":"C","hid":"0x6","translate":"C","code":"KeyC"},
{"keyCode":"68","functionType":"Singlekey","value":"D","hid":"0x7","translate":"D","code":"KeyD"},
{"keyCode":"69","functionType":"Singlekey","value":"E","hid":"0x8","translate":"E","code":"KeyE"},
{"keyCode":"70","functionType":"Singlekey","value":"F","hid":"0x9","translate":"F","code":"KeyF"},
{"keyCode":"71","functionType":"Singlekey","value":"G","hid":"0xa","translate":"G","code":"KeyG"},
{"keyCode":"72","functionType":"Singlekey","value":"H","hid":"0xb","translate":"H","code":"KeyH"},
{"keyCode":"73","functionType":"Singlekey","value":"I","hid":"0xc","translate":"I","code":"KeyI"},
{"keyCode":"74","functionType":"Singlekey","value":"J","hid":"0xd","translate":"J","code":"KeyJ"},
{"keyCode":"75","functionType":"Singlekey","value":"K","hid":"0xe","translate":"K","code":"KeyK"},
{"keyCode":"76","functionType":"Singlekey","value":"L","hid":"0xf","translate":"L","code":"KeyL"},
{"keyCode":"77","functionType":"Singlekey","value":"M","hid":"0x10","translate":"M","code":"KeyM"},
{"keyCode":"78","functionType":"Singlekey","value":"N","hid":"0x11","translate":"N","code":"KeyN"},
{"keyCode":"79","functionType":"Singlekey","value":"O","hid":"0x12","translate":"O","code":"KeyO"},
{"keyCode":"80","functionType":"Singlekey","value":"P","hid":"0x13","translate":"P","code":"KeyP"},
{"keyCode":"81","functionType":"Singlekey","value":"Q","hid":"0x14","translate":"Q","code":"KeyQ"},
{"keyCode":"82","functionType":"Singlekey","value":"R","hid":"0x15","translate":"R","code":"KeyR"},
{"keyCode":"83","functionType":"Singlekey","value":"S","hid":"0x16","translate":"S","code":"KeyS"},
{"keyCode":"84","functionType":"Singlekey","value":"T","hid":"0x17","translate":"T","code":"KeyT"},
{"keyCode":"85","functionType":"Singlekey","value":"U","hid":"0x18","translate":"U","code":"KeyU"},
{"keyCode":"86","functionType":"Singlekey","value":"V","hid":"0x19","translate":"V","code":"KeyV"},
{"keyCode":"87","functionType":"Singlekey","value":"W","hid":"0x1a","translate":"W","code":"KeyW"},
{"keyCode":"88","functionType":"Singlekey","value":"X","hid":"0x1b","translate":"X","code":"KeyX"},
{"keyCode":"89","functionType":"Singlekey","value":"Y","hid":"0x1c","translate":"Y","code":"KeyY"},
{"keyCode":"90","functionType":"Singlekey","value":"Z","hid":"0x1d","translate":"Z","code":"KeyZ"},
{"keyCode":"48","functionType":"Singlekey","value":"0","hid":"0x27","translate":"0","code":"Digit0"},
{"keyCode":"49","functionType":"Singlekey","value":"1","hid":"0x1e","translate":"1","code":"Digit1"},
{"keyCode":"50","functionType":"Singlekey","value":"2","hid":"0x1f","translate":"2","code":"Digit2"},
{"keyCode":"51","functionType":"Singlekey","value":"3","hid":"0x20","translate":"3","code":"Digit3"},
{"keyCode":"52","functionType":"Singlekey","value":"4","hid":"0x21","translate":"4","code":"Digit4"},
{"keyCode":"53","functionType":"Singlekey","value":"5","hid":"0x22","translate":"5","code":"Digit5"},
{"keyCode":"54","functionType":"Singlekey","value":"6","hid":"0x23","translate":"6","code":"Digit6"},
{"keyCode":"55","functionType":"Singlekey","value":"7","hid":"0x24","translate":"7","code":"Digit7"},
{"keyCode":"56","functionType":"Singlekey","value":"8","hid":"0x25","translate":"8","code":"Digit8"},
{"keyCode":"57","functionType":"Singlekey","value":"9","hid":"0x26","translate":"9","code":"Digit9"},
{"keyCode":"8","functionType":"Singlekey","value":"Backspace","hid":"0x2a","translate":"Backspace","code":"Backspace"},
{"keyCode":"9","functionType":"Singlekey","value":"Tab","hid":"0x2b","translate":"Tab","code":"Tab"},
{"keyCode":"144","functionType":"Singlekey","value":"Num Lock","hid":"0x53","translate":"Num Lock","code":"NumLock"},
{"keyCode":"13","functionType":"Singlekey","value":"Enter","hid":"0x28","translate":"Enter","code":"Enter"},
{"keyCode":"16","functionType":"Singlekey","value":"Shift","hid":"0xe1","translate":"Shift","code":"ShiftRight"},
{"keyCode":"17","functionType":"Singlekey","value":"Ctrl","hid":"0xe0","translate":"Ctrl","code":"ControlLeft"},
{"keyCode":"18","functionType":"Singlekey","value":"Alt","hid":"0xe2","translate":"Alt","code":"AltRight"},
{"keyCode":"19","functionType":"Singlekey","value":"Break","hid":"0x48","translate":"Break","code":"Pause"},
{"keyCode":"20","functionType":"Singlekey","value":"CapsLock","hid":"0x39","translate":"CapsLock","code":"CapsLock"},
{"keyCode":"27","functionType":"Singlekey","value":"Esc","hid":"0x29","translate":"Esc","code":"Escape"},
{"keyCode":"32","functionType":"Singlekey","value":"Space","hid":"0x2c","translate":"Space","code":"Space"},
{"keyCode":"33","functionType":"Singlekey","value":"PageUp","hid":"0x4b","translate":"PageUp","code":"Numpad9"},
{"keyCode":"34","functionType":"Singlekey","value":"PageDown","hid":"0x4e","translate":"PageDown","code":"Numpad3"},
{"keyCode":"35","functionType":"Singlekey","value":"End","hid":"0x4d","translate":"End","code":"Numpad1"},
{"keyCode":"36","functionType":"Singlekey","value":"Home","hid":"0x4a","translate":"Home","code":"Numpad7"},
{"keyCode":"37","functionType":"Singlekey","value":"Left","hid":"0x50","translate":"Left","code":"Numpad4"},
{"keyCode":"38","functionType":"Singlekey","value":"Up","hid":"0x52","translate":"Up","code":"Numpad8"},
{"keyCode":"39","functionType":"Singlekey","value":"Right","hid":"0x4f","translate":"Right","code":"Numpad6"},
{"keyCode":"40","functionType":"Singlekey","value":"Down","hid":"0x51","translate":"Down","code":"Numpad2"},
{"keyCode":"42","functionType":"Singlekey","value":"PRINT SCREEN","hid":"0x46","translate":"PRINT SCREEN"},
{"keyCode":"45","functionType":"Singlekey","value":"Insert","hid":"0x49","translate":"Insert","code":"Numpad0"},
{"keyCode":"46","functionType":"Singlekey","value":"Delete","hid":"0x4c","translate":"Delete","code":"NumpadDecimal"},
{"keyCode":"91","functionType":"Singlekey","value":"Left Win","hid":"0xe3","translate":"Left Win","code":"MetaLeft"},
{"keyCode":"92","functionType":"Singlekey","value":"Right Win","hid":"0xe3","translate":"Right Win"},
{"keyCode":"93","functionType":"Singlekey","value":"Menu","hid":"0x65","translate":"Menu","code":"ContextMenu"},
{"keyCode":"106","functionType":"Singlekey","value":"*","hid":"0x55","translate":"*","code":"NumpadMultiply"},
{"keyCode":"107","functionType":"Singlekey","value":"+","hid":"0x57","translate":"+","code":"NumpadAdd"},
{"keyCode":"109","functionType":"Singlekey","value":"-","hid":"0x56","translate":"-","code":"NumpadSubtract"},
{"keyCode":"111","functionType":"Singlekey","value":"/","hid":"0x54","translate":"/","code":"NumpadDivide"},
{"keyCode":"112","functionType":"Singlekey","value":"F1","hid":"0x3a","translate":"F1","code":"F1"},
{"keyCode":"113","functionType":"Singlekey","value":"F2","hid":"0x3b","translate":"F2","code":"F2"},
{"keyCode":"114","functionType":"Singlekey","value":"F3","hid":"0x3c","translate":"F3","code":"F3"},
{"keyCode":"115","functionType":"Singlekey","value":"F4","hid":"0x3d","translate":"F4","code":"F4"},
{"keyCode":"116","functionType":"Singlekey","value":"F5","hid":"0x3e","translate":"F5","code":"F5"},
{"keyCode":"117","functionType":"Singlekey","value":"F6","hid":"0x3f","translate":"F6","code":"F6"},
{"keyCode":"118","functionType":"Singlekey","value":"F7","hid":"0x40","translate":"F7","code":"F7"},
{"keyCode":"119","functionType":"Singlekey","value":"F8","hid":"0x41","translate":"F8","code":"F8"},
{"keyCode":"120","functionType":"Singlekey","value":"F9","hid":"0x42","translate":"F9","code":"F9"},
{"keyCode":"121","functionType":"Singlekey","value":"F10","hid":"0x43","translate":"F10","code":"F10"},
{"keyCode":"122","functionType":"Singlekey","value":"F11","hid":"0x44","translate":"F11","code":"F11"},
{"keyCode":"123","functionType":"Singlekey","value":"F12","hid":"0x45","translate":"F12","code":"F12"},
{"keyCode":"145","functionType":"Singlekey","value":"Scroll Lock","hid":"0x47","translate":"Scroll Lock","code":"ScrollLock"},
{"keyCode":"186","functionType":"Singlekey","value":";","hid":"0x33","translate":";","code":"Semicolon"},
{"keyCode":"187","functionType":"Singlekey","value":"=","hid":"0x2e","translate":"=","code":"Equal"},
{"keyCode":"188","functionType":"Singlekey","value":",","hid":"0x36","translate":",","code":"Comma"},
{"keyCode":"189","functionType":"Singlekey","value":"-","hid":"0x2d","translate":"-","code":"Minus"},
{"keyCode":"190","functionType":"Singlekey","value":"dot","hid":"0x37","translate":"dot","code":"Period"},
{"keyCode":"191","functionType":"Singlekey","value":"/","hid":"0x38","translate":"/","code":"Slash"},
{"keyCode":"192","functionType":"Singlekey","value":"~","hid":"0x35","translate":"~","code":"Backquote"},
{"keyCode":"219","functionType":"Singlekey","value":"[","hid":"0x2f","translate":"[","code":"BracketLeft"},
{"keyCode":"220","functionType":"Singlekey","value":"|","hid":"0x31","translate":"|","code":"Backslash"},
{"keyCode":"221","functionType":"Singlekey","value":"]","hid":"0x30","translate":"]","code":"BracketRight"},
{"keyCode":"222","functionType":"Singlekey","value":"'","hid":"0x34","translate":"'","code":"Quote"}]
