var AllFunctionMapping = [
    { keyCode: '65', functionType:'Singlekey', value: 'A',hid:'0x4', translate: 'A' },
    { keyCode: '66', functionType:'Singlekey', value: 'B',hid:'0x5', translate: 'B' },
    { keyCode: '67', functionType:'Singlekey', value: 'C',hid:'0x6', translate: 'C' },
    { keyCode: '68', functionType:'Singlekey', value: 'D',hid:'0x7', translate: 'D' },
    { keyCode: '69', functionType:'Singlekey', value: 'E',hid:'0x8', translate: 'E' },
    { keyCode: '70', functionType:'Singlekey', value: 'F',hid:'0x9', translate: 'F' },
    { keyCode: '71', functionType:'Singlekey', value: 'G',hid:'0xa', translate: 'G' },
    { keyCode: '72', functionType:'Singlekey', value: 'H',hid:'0xb', translate: 'H' },
    { keyCode: '73', functionType:'Singlekey', value: 'I',hid:'0xc', translate: 'I' },
    { keyCode: '74', functionType:'Singlekey', value: 'J',hid:'0xd', translate: 'J' },
    { keyCode: '75', functionType:'Singlekey', value: 'K',hid:'0xe', translate: 'K' },
    { keyCode: '76', functionType:'Singlekey', value: 'L',hid:'0xf', translate: 'L' },
    { keyCode: '77', functionType:'Singlekey', value: 'M',hid:'0x10', translate: 'M' },
    { keyCode: '78', functionType:'Singlekey', value: 'N',hid:'0x11', translate: 'N' },
    { keyCode: '79', functionType:'Singlekey', value: 'O',hid:'0x12', translate: 'O' },
    { keyCode: '80', functionType:'Singlekey', value: 'P',hid:'0x13', translate: 'P' },
    { keyCode: '81', functionType:'Singlekey', value: 'Q',hid:'0x14', translate: 'Q' },
    { keyCode: '82', functionType:'Singlekey', value: 'R',hid:'0x15', translate: 'R' },
    { keyCode: '83', functionType:'Singlekey', value: 'S',hid:'0x16', translate: 'S' },
    { keyCode: '84', functionType:'Singlekey', value: 'T',hid:'0x17', translate: 'T' },
    { keyCode: '85', functionType:'Singlekey', value: 'U',hid:'0x18', translate: 'U' },
    { keyCode: '86', functionType:'Singlekey', value: 'V',hid:'0x19', translate: 'V' },
    { keyCode: '87', functionType:'Singlekey', value: 'W',hid:'0x1a', translate: 'W' },
    { keyCode: '88', functionType:'Singlekey', value: 'X',hid:'0x1b', translate: 'X' },
    { keyCode: '89', functionType:'Singlekey', value: 'Y',hid:'0x1c', translate: 'Y' },
    { keyCode: '90', functionType:'Singlekey', value: 'Z',hid:'0x1d', translate: 'Z' },
    { keyCode: '48', functionType:'Singlekey', value: '0',hid:'0x27', translate: '0' },
    { keyCode: '49', functionType:'Singlekey', value: '1',hid:'0x1e', translate: '1' },
    { keyCode: '50', functionType:'Singlekey', value: '2',hid:'0x1f', translate: '2' },
    { keyCode: '51', functionType:'Singlekey', value: '3',hid:'0x20', translate: '3' },
    { keyCode: '52', functionType:'Singlekey', value: '4',hid:'0x21', translate: '4' },
    { keyCode: '53', functionType:'Singlekey', value: '5',hid:'0x22', translate: '5' },
    { keyCode: '54', functionType:'Singlekey', value: '6',hid:'0x23', translate: '6' },
    { keyCode: '55', functionType:'Singlekey', value: '7',hid:'0x24', translate: '7' },
    { keyCode: '56', functionType:'Singlekey', value: '8',hid:'0x25', translate: '8' },
    { keyCode: '57', functionType:'Singlekey', value: '9',hid:'0x26', translate: '9' },
    { keyCode: '8', functionType:'Singlekey', value: 'Backspace',hid:'0x2a', translate: 'Backspace' },
    { keyCode: '9', functionType:'Singlekey', value: 'Tab',hid:'0x2b', translate: 'Tab' },
    { keyCode: '144', functionType:'Singlekey', value: 'Num Lock',hid:'0x53', translate: 'Num Lock' },
    { keyCode: '13', functionType:'Singlekey', value: 'Enter',hid:'0x28', translate: 'Enter' },
    { keyCode: '16', functionType:'Singlekey', value: 'Shift',hid:'0xe1', translate: 'Shift' },
    { keyCode: '17', functionType:'Singlekey', value: 'Ctrl',hid:'0xe0', translate: 'Ctrl' },
    { keyCode: '18', functionType:'Singlekey', value: 'Alt',hid:'0xe2', translate: 'Alt' },
    { keyCode: '19', functionType:'Singlekey', value: 'Break',hid:'0x48', translate: 'Break' },
    { keyCode: '20', functionType:'Singlekey', value: 'CapsLock',hid:'0x39', translate: 'CapsLock' },
    { keyCode: '27', functionType:'Singlekey', value: 'Esc',hid:'0x29', translate: 'Esc' },
    { keyCode: '32', functionType:'Singlekey', value: 'Space',hid:'0x2c', translate: 'Space' },
    { keyCode: '33', functionType:'Singlekey', value: 'PageUp',hid:'0x4b', translate: 'PageUp' },
    { keyCode: '34', functionType:'Singlekey', value: 'PageDown',hid:'0x4e', translate: 'PageDown' },
    { keyCode: '35', functionType:'Singlekey', value: 'End',hid:'0x4d', translate: 'End' },
    { keyCode: '36', functionType:'Singlekey', value: 'Home',hid:'0x4a', translate: 'Home' },
    { keyCode: '37', functionType:'Singlekey', value: 'Left',hid:'0x50', translate: 'Left' },
    { keyCode: '38', functionType:'Singlekey', value: 'Up',hid:'0x52', translate: 'Up' },
    { keyCode: '39', functionType:'Singlekey', value: 'Right',hid:'0x4f', translate: 'Right' },
    { keyCode: '40', functionType:'Singlekey', value: 'Down',hid:'0x51', translate: 'Down' },
    { keyCode: '42', functionType:'Singlekey', value: 'PRINT SCREEN',hid:'0x46', translate: 'PRINT SCREEN' },
    { keyCode: '45', functionType:'Singlekey', value: 'Insert',hid:'0x49', translate: 'Insert' },
    { keyCode: '46', functionType:'Singlekey', value: 'Delete',hid:'0x4c', translate: 'Delete' },
    { keyCode: '91', functionType:'Singlekey', value: 'Left Win',hid:'0xe3', translate: 'Left Win' },
    { keyCode: '92', functionType:'Singlekey', value: 'Right Win',hid:'0xe3', translate: 'Right Win' },
    { keyCode: '93', functionType:'Singlekey', value: 'Menu',hid:'0x65', translate: 'Menu' },
    { keyCode: '96', functionType:'Singlekey', value: 'Num 0',hid:'0x62', translate: 'Num 0' },
    { keyCode: '97', functionType:'Singlekey', value: 'Num 1',hid:'0x59', translate: 'Num 1' },
    { keyCode: '98', functionType:'Singlekey', value: 'Num 2',hid:'0x5a', translate: 'Num 2' },
    { keyCode: '99', functionType:'Singlekey', value: 'Num 3',hid:'0x5b', translate: 'Num 3' },
    { keyCode: '100', functionType:'Singlekey', value: 'Num 4',hid:'0x5c', translate: 'Num 4' },
    { keyCode: '101', functionType:'Singlekey', value: 'Num 5',hid:'0x5d', translate: 'Num 5' },
    { keyCode: '102', functionType:'Singlekey', value: 'Num 6',hid:'0x5e', translate: 'Num 6' },
    { keyCode: '103', functionType:'Singlekey', value: 'Num 7',hid:'0x5f', translate: 'Num 7' },
    { keyCode: '104', functionType:'Singlekey', value: 'Num 8',hid:'0x60', translate: 'Num 8' },
    { keyCode: '105', functionType:'Singlekey', value: 'Num 9',hid:'0x61', translate: 'Num 9' },
    { keyCode: '106', functionType:'Singlekey', value: '*',hid:'0x55', translate: '*' },
    { keyCode: '107', functionType:'Singlekey', value: '+',hid:'0x57', translate: '+' },
    { keyCode: '109', functionType:'Singlekey', value: '-',hid:'0x56', translate: '-' },
    { keyCode: '110', functionType:'Singlekey', value: 'Numdot',hid:'0x63', translate: 'Numdot' },
    { keyCode: '111', functionType:'Singlekey', value: '/',hid:'0x54', translate: '/' },
    { keyCode: '112', functionType:'Singlekey', value: 'F1',hid:'0x3a', translate: 'F1' },
    { keyCode: '113', functionType:'Singlekey', value: 'F2',hid:'0x3b', translate: 'F2' },
    { keyCode: '114', functionType:'Singlekey', value: 'F3',hid:'0x3c', translate: 'F3' },
    { keyCode: '115', functionType:'Singlekey', value: 'F4',hid:'0x3d', translate: 'F4' },
    { keyCode: '116', functionType:'Singlekey', value: 'F5',hid:'0x3e', translate: 'F5' },
    { keyCode: '117', functionType:'Singlekey', value: 'F6',hid:'0x3f', translate: 'F6' },
    { keyCode: '118', functionType:'Singlekey', value: 'F7',hid:'0x40', translate: 'F7' },
    { keyCode: '119', functionType:'Singlekey', value: 'F8',hid:'0x41', translate: 'F8' },
    { keyCode: '120', functionType:'Singlekey', value: 'F9',hid:'0x42', translate: 'F9' },
    { keyCode: '121', functionType:'Singlekey', value: 'F10',hid:'0x43', translate: 'F10' },
    { keyCode: '122', functionType:'Singlekey', value: 'F11',hid:'0x44', translate: 'F11' },
    { keyCode: '123', functionType:'Singlekey', value: 'F12',hid:'0x45', translate: 'F12' },
    { keyCode: '145', functionType:'Singlekey', value: 'Scroll Lock',hid:'0x47', translate: 'Scroll Lock' },
    { keyCode: '186', functionType:'Singlekey', value: ';',hid:'0x33', translate: ';' },
    { keyCode: '187', functionType:'Singlekey', value: '=',hid:'0x2e', translate: '=' },
    { keyCode: '188', functionType:'Singlekey', value: ',',hid:'0x36', translate: ',' },
    { keyCode: '189', functionType:'Singlekey', value: '-',hid:'0x2d', translate: '-' },
    { keyCode: '190', functionType:'Singlekey', value: 'dot',hid:'0x37', translate: 'dot' },
    { keyCode: '191', functionType:'Singlekey', value: '/',hid:'0x38', translate: '/' },
    { keyCode: '192', functionType:'Singlekey', value: '~',hid:'0x35', translate: '~' },
    { keyCode: '219', functionType:'Singlekey', value: '[',hid:'0x2f', translate: '[' },
    { keyCode: '220', functionType:'Singlekey', value: '|',hid:'0x31', translate: '|' },
    { keyCode: '221', functionType:'Singlekey', value: ']',hid:'0x30', translate: ']' },
    { keyCode: '222', functionType:'Singlekey', value: "'",hid:'0x34', translate: "'" },
    { keyCode: 'Multimedia_Fun_0', functionType:'Multimedia', value: 'Media Player',hid:'0x999',  translate: 'Media Player' },
    { keyCode: 'Multimedia_Fun_1', functionType:'Multimedia', value: 'Play/Pause',hid:'0x0998',  translate: 'Play/Pause' },
    { keyCode: 'Multimedia_Fun_2', functionType:'Multimedia', value: 'Next',hid:'0x0997',  translate: 'Next' },
    { keyCode: 'Multimedia_Fun_3', functionType:'Multimedia', value: 'Previous',hid:'0x996',  translate: 'Previous' },
    { keyCode: 'Multimedia_Fun_4', functionType:'Multimedia', value: 'Stop',hid:'0x995',  translate: 'Stop' },
    { keyCode: 'Multimedia_Fun_5', functionType:'Multimedia', value: 'Mute',hid:'0x994',  translate: 'Mute' },
    { keyCode: 'Multimedia_Fun_6', functionType:'Multimedia', value: 'Volume up',hid:'0x993',  translate: 'Volume up' },
    { keyCode: 'Multimedia_Fun_7', functionType:'Multimedia', value: 'Volume down',hid:'0x992',  translate: 'Volume down' },
    { keyCode: 'Multimedia_Fun_8', functionType:'Multimedia', value: 'Next track',hid:'0x991',  translate: 'Next trac' },
    { keyCode: 'Multimedia_Fun_9', functionType:'Multimedia', value: 'Previoustrack',hid:'0x990',  translate: 'Previoustrack', },
    { keyCode: 'KEYBOARD_Fun_10', functionType:'KEYBOARD', value: 'Profilecycleup',hid:'0x899',  translate: 'Profilecycleup', },
    { keyCode: 'KEYBOARD_Fun_11', functionType:'KEYBOARD', value: 'Profilecycledown',hid:'0x898',  translate: 'Profilecycledown', },
    { keyCode: 'KEYBOARD_Fun_12', functionType:'KEYBOARD', value: 'Layercycleup',hid:'0x897',  translate: 'Layercycleup' },
    { keyCode: 'KEYBOARD_Fun_13', functionType:'KEYBOARD', value: 'Layercycledown',hid:'0x896',  translate: 'Layercycledown', },
    { keyCode: 'MOUSE_Fun_14', functionType:'MOUSE', value: 'Leftbutton',hid:'0x895',  translate: 'Leftbutton' },
    { keyCode: 'MOUSE_Fun_15', functionType:'MOUSE', value: 'Rightbutton',hid:'0x894',  translate: 'Rightbutton' },
    { keyCode: 'MOUSE_Fun_16', functionType:'MOUSE', value: 'Middlebutton',hid:'0x893',  translate: 'Middlebutton' },
    { keyCode: 'MOUSE_Fun_17', functionType:'MOUSE', value: 'Forward',hid:'0x892',  translate: 'Forward' },
    { keyCode: 'MOUSE_Fun_18', functionType:'MOUSE', value: 'Back',hid:'0x891',  translate: 'Back' },
    { keyCode: 'MOUSE_Fun_19', functionType:'MOUSE', value: 'Scrollup',hid:'0x890',  translate: 'Scrollup' },
    { keyCode: 'MOUSE_Fun_20', functionType:'MOUSE', value: 'Scrolldown',hid:'0x799',  translate: 'Scrolldown' },
    { keyCode: 'MOUSE_Fun_21', functionType:'MOUSE', value: 'Profilecycleup',hid:'0x798',  translate: 'Profilecycleup' },
    { keyCode: 'MOUSE_Fun_22', functionType:'MOUSE', value: 'Profilecycledown',hid:'0x797',  translate: 'Profilecycledown' },
    { keyCode: 'MOUSE_Fun_23', functionType:'MOUSE', value: 'Batterystatuscheck',hid:'0x796',  translate: 'Batterystatuscheck', },
    { keyCode: 'LaunchProgram', functionType:'LaunchProgram', value: 'LaunchProgram',hid:'0x795',  translate: 'LaunchProgram' },
    { keyCode: 'LaunchWebsite', functionType:'LaunchProgram', value: 'LaunchWebsite',hid:'0x794',  translate: 'LaunchWebsite' },
    { keyCode: 'Shortcuts_Fun_25', functionType:'Shortcuts', value: 'Email',hid:'0x793',  translate: 'Email' },
    { keyCode: 'Shortcuts_Fun_26', functionType:'Shortcuts', value: 'Calculator',hid:'0x792',  translate: 'Calculator' },
    { keyCode: 'Shortcuts_Fun_27', functionType:'Shortcuts', value: 'My Computer',hid:'0x791',  translate: 'My Computer' },
    { keyCode: 'Shortcuts_Fun_28', functionType:'Shortcuts', value: 'Explorer',hid:'0x790',  translate: 'Explorer' },
    { keyCode: 'Shortcuts_Fun_29', functionType:'Shortcuts', value: 'WWW Home',hid:'0x789',  translate: 'WWW Home' },
    { keyCode: 'Shortcuts_Fun_30', functionType:'Shortcuts', value: 'WWW Refresh',hid:'0x788',  translate: 'WWW Refresh' },
    { keyCode: 'Shortcuts_Fun_31', functionType:'Shortcuts', value: 'WWW Stop',hid:'0x787',  translate: 'WWW Stop' },
    { keyCode: 'Shortcuts_Fun_32', functionType:'Shortcuts', value: 'WWW Back',hid:'0x786',  translate: 'WWW Back' },
    { keyCode: 'Shortcuts_Fun_33', functionType:'Shortcuts', value: 'WWW Forward',hid:'0x785',  translate: 'WWW Forward' },
    { keyCode: 'Shortcuts_Fun_34', functionType:'Shortcuts', value: 'WWW Search',hid:'0x784',  translate: 'WWW Search' },
    { keyCode: 'MacroFunction', functionType:'MacroFunction', value: 'MacroFunction',hid:'0x783',  translate: 'MacroFunction' },
    { keyCode: 'ScrollWheel', functionType:'ScrollWheel', value: 'ScrollWheel',hid:'0x782',  translate: 'ScrollWheel' },
    { keyCode: 'Custom_Fnkey', functionType:'Custom_Fnkey', value: 'FN',hid:'0x781',  translate: 'FN' },
    { keyCode: '0', functionType:'Singlekey', value: 'Left Click',hid:'0x780', translate: 'Left Click' },
    { keyCode: '1', functionType:'Singlekey', value: 'Scroll Click',hid:'0x779',  translate: 'Scroll Click' },
    { keyCode: '2', functionType:'Singlekey', value: 'Right Click',hid:'0x778',  translate: 'Right Click' },
    { keyCode: '3', functionType:'Singlekey', value: 'Back',hid:'0x777',  translate: 'Back' },
    { keyCode: '4',functionType:'Singlekey', value: 'Forward',hid:'0x776',  translate: 'Forward' },
]
// { keyCode: 'ScrollWheel2', functionType:'ScrollWheel2', value: 'ScrollWheel2',hid:'0x775',  translate: 'ScrollWheel2' },





