var SupportLanguage = [
    { name: 'ENGLISH', value: 'en' },
    // {name:'繁體中文', value:"tw"},
    // {name:'简体中文', value:"cn"}
]
exports.SupportLanguage = SupportLanguage
//Keyboard Buttontype:0
var MouseMapping = [
    { keyCode: '0', hid: 0x01, value: 'Left Click', translate: 'Left Click' },
    { keyCode: '1', hid: 0x03, value: 'Scroll Click', translate: 'Scroll Click' },
    { keyCode: '2', hid: 0x02, value: 'Right Click', translate: 'Right Click' },
    { keyCode: '3', hid: 0x02, value: 'Back', translate: 'Back' },
    { keyCode: '4', hid: 0x02, value: 'Forward', translate: 'Forward' },

]

var KeyMapping = [
    { keyCode: '65', value: 'A', hid: 0x4, translate: 'A' },
    { keyCode: '66', value: 'B', hid: 0x5, translate: 'B' },
    { keyCode: '67', value: 'C', hid: 0x6, translate: 'C' },
    { keyCode: '68', value: 'D', hid: 0x7, translate: 'D' },
    { keyCode: '69', value: 'E', hid: 0x8, translate: 'E' },
    { keyCode: '70', value: 'F', hid: 0x9, translate: 'F' },
    { keyCode: '71', value: 'G', hid: 0xa, translate: 'G' },
    { keyCode: '72', value: 'H', hid: 0xb, translate: 'H' },
    { keyCode: '73', value: 'I', hid: 0xc, translate: 'I' },
    { keyCode: '74', value: 'J', hid: 0xd, translate: 'J' },
    { keyCode: '75', value: 'K', hid: 0xe, translate: 'K' },
    { keyCode: '76', value: 'L', hid: 0xf, translate: 'L' },
    { keyCode: '77', value: 'M', hid: 0x10, translate: 'M' },
    { keyCode: '78', value: 'N', hid: 0x11, translate: 'N' },
    { keyCode: '79', value: 'O', hid: 0x12, translate: 'O' },
    { keyCode: '80', value: 'P', hid: 0x13, translate: 'P' },
    { keyCode: '81', value: 'Q', hid: 0x14, translate: 'Q' },
    { keyCode: '82', value: 'R', hid: 0x15, translate: 'R' },
    { keyCode: '83', value: 'S', hid: 0x16, translate: 'S' },
    { keyCode: '84', value: 'T', hid: 0x17, translate: 'T' },
    { keyCode: '85', value: 'U', hid: 0x18, translate: 'U' },
    { keyCode: '86', value: 'V', hid: 0x19, translate: 'V' },
    { keyCode: '87', value: 'W', hid: 0x1a, translate: 'W' },
    { keyCode: '88', value: 'X', hid: 0x1b, translate: 'X' },
    { keyCode: '89', value: 'Y', hid: 0x1c, translate: 'Y' },
    { keyCode: '90', value: 'Z', hid: 0x1d, translate: 'Z' },
    { keyCode: '48', value: '0', hid: 0x27, translate: '0' },
    { keyCode: '49', value: '1', hid: 0x1e, translate: '1' },
    { keyCode: '50', value: '2', hid: 0x1f, translate: '2' },
    { keyCode: '51', value: '3', hid: 0x20, translate: '3' },
    { keyCode: '52', value: '4', hid: 0x21, translate: '4' },
    { keyCode: '53', value: '5', hid: 0x22, translate: '5' },
    { keyCode: '54', value: '6', hid: 0x23, translate: '6' },
    { keyCode: '55', value: '7', hid: 0x24, translate: '7' },
    { keyCode: '56', value: '8', hid: 0x25, translate: '8' },
    { keyCode: '57', value: '9', hid: 0x26, translate: '9' },
    { keyCode: '8', value: 'Backspace', hid: 0x2a, translate: 'Backspace' },
    { keyCode: '9', value: 'Tab', hid: 0x2b, translate: 'Tab' },
    { keyCode: '144', value: 'Num Lock', hid: 0x53, translate: 'Num Lock' },
    { keyCode: '13', value: 'Enter', hid: 0x28, translate: 'Enter' },
    { keyCode: '16', value: 'Shift', hid: 0xe1, Modifier:0x02, translate: 'Shift' },
    { keyCode: '17', value: 'Ctrl', hid: 0xe0, Modifier:0x01, translate: 'Ctrl' },
    { keyCode: '18', value: 'Alt', hid: 0xe2, Modifier:0x04, translate: 'Alt' },
    { keyCode: '19', value: 'Break', hid: 0x48, translate: 'Break' },
    { keyCode: '20', value: 'CapsLock', hid: 0x39, translate: 'CapsLock' },
    { keyCode: '27', value: 'Esc', hid: 0x29, translate: 'Esc' },
    { keyCode: '32', value: 'Space', hid: 0x2c, translate: 'Space' },
    { keyCode: '33', value: 'PageUp', hid: 0x4b, translate: 'PageUp' },
    { keyCode: '34', value: 'PageDown', hid: 0x4e, translate: 'PageDown' },
    { keyCode: '35', value: 'End', hid: 0x4d, translate: 'End' },
    { keyCode: '36', value: 'Home', hid: 0x4a, translate: 'Home' },
    { keyCode: '37', value: 'Left', hid: 0x50, translate: 'Left' },
    { keyCode: '38', value: 'Up', hid: 0x52, translate: 'Up' },
    { keyCode: '39', value: 'Right', hid: 0x4f, translate: 'Right' },
    { keyCode: '40', value: 'Down', hid: 0x51, translate: 'Down' },
    { keyCode: '42', value: 'PRINT SCREEN', hid: 0x46, translate: 'PRINT SCREEN' },
    { keyCode: '45', value: 'Insert', hid: 0x49, translate: 'Insert' },
    { keyCode: '46', value: 'Delete', hid: 0x4c, translate: 'Delete' },
    { keyCode: '91', value: 'Left Win', hid: 0xe3, Modifier:0x08, translate: 'Left Win' },
    { keyCode: '92', value: 'Right Win', hid: 0xe3, Modifier:0x80, translate: 'Right Win' },
    { keyCode: '93', value: 'Menu', hid: 0x65, translate: 'Menu' },
    { keyCode: '96', value: 'Num 0', hid: 0x62, translate: 'Num 0' },
    { keyCode: '97', value: 'Num 1', hid: 0x59, translate: 'Num 1' },
    { keyCode: '98', value: 'Num 2', hid: 0x5a, translate: 'Num 2' },
    { keyCode: '99', value: 'Num 3', hid: 0x5b, translate: 'Num 3' },
    { keyCode: '100', value: 'Num 4', hid: 0x5c, translate: 'Num 4' },
    { keyCode: '101', value: 'Num 5', hid: 0x5d, translate: 'Num 5' },
    { keyCode: '102', value: 'Num 6', hid: 0x5e, translate: 'Num 6' },
    { keyCode: '103', value: 'Num 7', hid: 0x5f, translate: 'Num 7' },
    { keyCode: '104', value: 'Num 8', hid: 0x60, translate: 'Num 8' },
    { keyCode: '105', value: 'Num 9', hid: 0x61, translate: 'Num 9' },
    { keyCode: '106', value: '*', hid: 0x55, translate: '*' },
    { keyCode: '107', value: '+', hid: 0x57, translate: '+' },
    { keyCode: '109', value: '-', hid: 0x56, translate: '-' },
    { keyCode: '110', value: 'Numdot', hid: 0x63, translate: 'Numdot' },
    { keyCode: '111', value: '/', hid: 0x54, translate: '/' },
    { keyCode: '112', value: 'F1', hid: 0x3a, translate: 'F1' },
    { keyCode: '113', value: 'F2', hid: 0x3b, translate: 'F2' },
    { keyCode: '114', value: 'F3', hid: 0x3c, translate: 'F3' },
    { keyCode: '115', value: 'F4', hid: 0x3d, translate: 'F4' },
    { keyCode: '116', value: 'F5', hid: 0x3e, translate: 'F5' },
    { keyCode: '117', value: 'F6', hid: 0x3f, translate: 'F6' },
    { keyCode: '118', value: 'F7', hid: 0x40, translate: 'F7' },
    { keyCode: '119', value: 'F8', hid: 0x41, translate: 'F8' },
    { keyCode: '120', value: 'F9', hid: 0x42, translate: 'F9' },
    { keyCode: '121', value: 'F10', hid: 0x43, translate: 'F10' },
    { keyCode: '122', value: 'F11', hid: 0x44, translate: 'F11' },
    { keyCode: '123', value: 'F12', hid: 0x45, translate: 'F12' },
    // {keyCode:'136', value:'Num Lock', hid:0x83, translate:"Num Lock"},
    { keyCode: '145', value: 'Scoll Lock', hid: 0x47, translate: 'Scoll Lock' },
    // {keyCode:'144', value:'Num Lock', hid:0x53, translate:"Num Lock"},
    { keyCode: '186', value: ';', hid: 0x33, translate: ';' },
    { keyCode: '187', value: '=', hid: 0x2e, translate: '=' },
    { keyCode: '188', value: ',', hid: 0x36, translate: ',' },
    { keyCode: '189', value: '-', hid: 0x2d, translate: '-' },
    { keyCode: '190', value: 'dot', hid: 0x37, translate: 'dot' },
    { keyCode: '191', value: '/', hid: 0x38, translate: '/' },
    { keyCode: '192', value: '~', hid: 0x35, translate: '~' },
    { keyCode: '219', value: '[', hid: 0x2f, translate: '[' },
    { keyCode: '220', value: '|', hid: 0x31, translate: '|' },
    { keyCode: '221', value: ']', hid: 0x30, translate: ']' },
    { keyCode: '222', value: "'", hid: 0x34, translate: "'" },
]
var MediaMapping = [
    { keyCode: '1', value: 'None', hid: 0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Media Player', hid: 0x04, hidMap: [0x01, 0x83], translate: '' },
    { keyCode: '1', value: 'Play/Pause', hid: 0x04, hidMap: [0x00, 0xcd], translate: '' },
    { keyCode: '1', value: 'Next', hid: 0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous', hid: 0x04, hidMap: [0x00, 0xb6], translate: '' },
    { keyCode: '1', value: 'Stop', hid: 0x04, hidMap: [0x00, 0xb7], translate: '' },
    { keyCode: '1', value: 'Mute', hid: 0x04, hidMap: [0x00, 0xe2], translate: '' },
    { keyCode: '1', value: 'Volume up', hid: 0x04, hidMap: [0x00, 0xe9], translate: '' },
    { keyCode: '1', value: 'Volume down', hid: 0x04, hidMap: [0x00, 0xea], translate: '' },
    { keyCode: '1', value: 'Next track', hid: 0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous track', hid: 0x04, hidMap: [0x00, 0xb6], translate: '' },
]
var WindowsMapping = [
    { keyCode: '1', value: 'None', hid: 0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Email', hid: 0x04, hidMap: [0x01, 0x8a], translate: '' },
    { keyCode: '1', value: 'Calculator', hid: 0x04, hidMap: [0x01, 0x92], translate: '' },
    { keyCode: '1', value: 'My Computer', hid: 0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'Explorer', hid: 0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'WWW Home', hid: 0x04, hidMap: [0x02, 0x23], translate: '' },
    { keyCode: '1', value: 'WWW Refresh', hid: 0x04, hidMap: [0x02, 0x27], translate: '' },
    { keyCode: '1', value: 'WWW Stop', hid: 0x04, hidMap: [0x02, 0x26], translate: '' },
    { keyCode: '1', value: 'WWW Back', hid: 0x04, hidMap: [0x02, 0x24], translate: '' },
    { keyCode: '1', value: 'WWW Forward', hid: 0x04, hidMap: [0x02, 0x25], translate: '' },
    { keyCode: '1', value: 'WWW Search', hid: 0x04, hidMap: [0x02, 0x21], translate: '' },
]

//finalIndexFunction=35
var Shortcuts_WindowsMapping=[
    { keyCode: 'Shortcuts_Fun_25', value: 'Email', hid: 0x04, hidMap: [0x01, 0x8a], translate: 'Email' },
    { keyCode: 'Shortcuts_Fun_26', value: 'Calculator', hid: 0x04, hidMap: [0x01, 0x92], translate: 'Calculator' },
    { keyCode: 'Shortcuts_Fun_27', value: 'My Computer', hid: 0x04, hidMap: [0x01, 0x94], translate: 'My Computer' },
    { keyCode: 'Shortcuts_Fun_28', value: 'Explorer', hid: 0x04, hidMap: [0x01, 0x94], translate: 'Explorer' },
    { keyCode: 'Shortcuts_Fun_29', value: 'WWW Home', hid: 0x04, hidMap: [0x02, 0x23], translate: 'WWW Home' },
    { keyCode: 'Shortcuts_Fun_30', value: 'WWW Refresh', hid: 0x04, hidMap: [0x02, 0x27], translate: 'WWW Refresh' },
    { keyCode: 'Shortcuts_Fun_31', value: 'WWW Stop', hid: 0x04, hidMap: [0x02, 0x26], translate: 'WWW Stop' },
    { keyCode: 'Shortcuts_Fun_32', value: 'WWW Back', hid: 0x04, hidMap: [0x02, 0x24], translate: 'WWW Back' },
    { keyCode: 'Shortcuts_Fun_33', value: 'WWW Forward', hid: 0x04, hidMap: [0x02, 0x25], translate: 'WWW Forward' },
    { keyCode: 'Shortcuts_Fun_34', value: 'WWW Search', hid: 0x04, hidMap: [0x02, 0x21], translate: 'WWW Search' },
]


var AllFunctionMapping = [
    { keyCode: '65', functionType:'Singlekey', value: 'A',hid:'0x4', translate: 'A' },
    { keyCode: '66', functionType:'Singlekey', value: 'B',hid:'0x5', translate: 'B' },
    { keyCode: '67', functionType:'Singlekey', value: 'C',hid:'0x6', translate: 'C' },
    { keyCode: '68', functionType:'Singlekey', value: 'D',hid:'0x7', translate: 'D' },
    { keyCode: '69', functionType:'Singlekey', value: 'E',hid:'0x8', translate: 'E' },
    { keyCode: '70', functionType:'Singlekey', value: 'F',hid:'0x9', translate: 'F' },
    { keyCode: '71', functionType:'Singlekey', value: 'G',hid:'0xa', translate: 'G' },
    { keyCode: '72', functionType:'Singlekey', value: 'H',hid:'0xb', translate: 'H' },
    { keyCode: '73', functionType:'Singlekey', value: 'I',hid:'0xc', translate: 'I' },
    { keyCode: '74', functionType:'Singlekey', value: 'J',hid:'0xd', translate: 'J' },
    { keyCode: '75', functionType:'Singlekey', value: 'K',hid:'0xe', translate: 'K' },
    { keyCode: '76', functionType:'Singlekey', value: 'L',hid:'0xf', translate: 'L' },
    { keyCode: '77', functionType:'Singlekey', value: 'M',hid:'0x10', translate: 'M' },
    { keyCode: '78', functionType:'Singlekey', value: 'N',hid:'0x11', translate: 'N' },
    { keyCode: '79', functionType:'Singlekey', value: 'O',hid:'0x12', translate: 'O' },
    { keyCode: '80', functionType:'Singlekey', value: 'P',hid:'0x13', translate: 'P' },
    { keyCode: '81', functionType:'Singlekey', value: 'Q',hid:'0x14', translate: 'Q' },
    { keyCode: '82', functionType:'Singlekey', value: 'R',hid:'0x15', translate: 'R' },
    { keyCode: '83', functionType:'Singlekey', value: 'S',hid:'0x16', translate: 'S' },
    { keyCode: '84', functionType:'Singlekey', value: 'T',hid:'0x17', translate: 'T' },
    { keyCode: '85', functionType:'Singlekey', value: 'U',hid:'0x18', translate: 'U' },
    { keyCode: '86', functionType:'Singlekey', value: 'V',hid:'0x19', translate: 'V' },
    { keyCode: '87', functionType:'Singlekey', value: 'W',hid:'0x1a', translate: 'W' },
    { keyCode: '88', functionType:'Singlekey', value: 'X',hid:'0x1b', translate: 'X' },
    { keyCode: '89', functionType:'Singlekey', value: 'Y',hid:'0x1c', translate: 'Y' },
    { keyCode: '90', functionType:'Singlekey', value: 'Z',hid:'0x1d', translate: 'Z' },
    { keyCode: '48', functionType:'Singlekey', value: '0',hid:'0x27', translate: '0' },
    { keyCode: '49', functionType:'Singlekey', value: '1',hid:'0x1e', translate: '1' },
    { keyCode: '50', functionType:'Singlekey', value: '2',hid:'0x1f', translate: '2' },
    { keyCode: '51', functionType:'Singlekey', value: '3',hid:'0x20', translate: '3' },
    { keyCode: '52', functionType:'Singlekey', value: '4',hid:'0x21', translate: '4' },
    { keyCode: '53', functionType:'Singlekey', value: '5',hid:'0x22', translate: '5' },
    { keyCode: '54', functionType:'Singlekey', value: '6',hid:'0x23', translate: '6' },
    { keyCode: '55', functionType:'Singlekey', value: '7',hid:'0x24', translate: '7' },
    { keyCode: '56', functionType:'Singlekey', value: '8',hid:'0x25', translate: '8' },
    { keyCode: '57', functionType:'Singlekey', value: '9',hid:'0x26', translate: '9' },
    { keyCode: '8', functionType:'Singlekey', value: 'Backspace',hid:'0x2a', translate: 'Backspace' },
    { keyCode: '9', functionType:'Singlekey', value: 'Tab',hid:'0x2b', translate: 'Tab' },
    { keyCode: '144', functionType:'Singlekey', value: 'Num Lock',hid:'0x53', translate: 'Num Lock' },
    { keyCode: '13', functionType:'Singlekey', value: 'Enter',hid:'0x28', translate: 'Enter' },
    { keyCode: '16', functionType:'Singlekey', value: 'Shift',hid:'0xe1', translate: 'Shift' },
    { keyCode: '17', functionType:'Singlekey', value: 'Ctrl',hid:'0xe0', translate: 'Ctrl' },
    { keyCode: '18', functionType:'Singlekey', value: 'Alt',hid:'0xe2', translate: 'Alt' },
    { keyCode: '19', functionType:'Singlekey', value: 'Break',hid:'0x48', translate: 'Break' },
    { keyCode: '20', functionType:'Singlekey', value: 'CapsLock',hid:'0x39', translate: 'CapsLock' },
    { keyCode: '27', functionType:'Singlekey', value: 'Esc',hid:'0x29', translate: 'Esc' },
    { keyCode: '32', functionType:'Singlekey', value: 'Space',hid:'0x2c', translate: 'Space' },
    { keyCode: '33', functionType:'Singlekey', value: 'PageUp',hid:'0x4b', translate: 'PageUp' },
    { keyCode: '34', functionType:'Singlekey', value: 'PageDown',hid:'0x4e', translate: 'PageDown' },
    { keyCode: '35', functionType:'Singlekey', value: 'End',hid:'0x4d', translate: 'End' },
    { keyCode: '36', functionType:'Singlekey', value: 'Home',hid:'0x4a', translate: 'Home' },
    { keyCode: '37', functionType:'Singlekey', value: 'Left',hid:'0x50', translate: 'Left' },
    { keyCode: '38', functionType:'Singlekey', value: 'Up',hid:'0x52', translate: 'Up' },
    { keyCode: '39', functionType:'Singlekey', value: 'Right',hid:'0x4f', translate: 'Right' },
    { keyCode: '40', functionType:'Singlekey', value: 'Down',hid:'0x51', translate: 'Down' },
    { keyCode: '42', functionType:'Singlekey', value: 'PRINT SCREEN',hid:'0x46', translate: 'PRINT SCREEN' },
    { keyCode: '45', functionType:'Singlekey', value: 'Insert',hid:'0x49', translate: 'Insert' },
    { keyCode: '46', functionType:'Singlekey', value: 'Delete',hid:'0x4c', translate: 'Delete' },
    { keyCode: '91', functionType:'Singlekey', value: 'Left Win',hid:'0xe3', translate: 'Left Win' },
    { keyCode: '92', functionType:'Singlekey', value: 'Right Win',hid:'0xe3', translate: 'Right Win' },
    { keyCode: '93', functionType:'Singlekey', value: 'Menu',hid:'0x65', translate: 'Menu' },
    { keyCode: '96', functionType:'Singlekey', value: 'Num 0',hid:'0x62', translate: 'Num 0' },
    { keyCode: '97', functionType:'Singlekey', value: 'Num 1',hid:'0x59', translate: 'Num 1' },
    { keyCode: '98', functionType:'Singlekey', value: 'Num 2',hid:'0x5a', translate: 'Num 2' },
    { keyCode: '99', functionType:'Singlekey', value: 'Num 3',hid:'0x5b', translate: 'Num 3' },
    { keyCode: '100', functionType:'Singlekey', value: 'Num 4',hid:'0x5c', translate: 'Num 4' },
    { keyCode: '101', functionType:'Singlekey', value: 'Num 5',hid:'0x5d', translate: 'Num 5' },
    { keyCode: '102', functionType:'Singlekey', value: 'Num 6',hid:'0x5e', translate: 'Num 6' },
    { keyCode: '103', functionType:'Singlekey', value: 'Num 7',hid:'0x5f', translate: 'Num 7' },
    { keyCode: '104', functionType:'Singlekey', value: 'Num 8',hid:'0x60', translate: 'Num 8' },
    { keyCode: '105', functionType:'Singlekey', value: 'Num 9',hid:'0x61', translate: 'Num 9' },
    { keyCode: '106', functionType:'Singlekey', value: '*',hid:'0x55', translate: '*' },
    { keyCode: '107', functionType:'Singlekey', value: '+',hid:'0x57', translate: '+' },
    { keyCode: '109', functionType:'Singlekey', value: '-',hid:'0x56', translate: '-' },
    { keyCode: '110', functionType:'Singlekey', value: 'Numdot',hid:'0x63', translate: 'Numdot' },
    { keyCode: '111', functionType:'Singlekey', value: '/',hid:'0x54', translate: '/' },
    { keyCode: '112', functionType:'Singlekey', value: 'F1',hid:'0x3a', translate: 'F1' },
    { keyCode: '113', functionType:'Singlekey', value: 'F2',hid:'0x3b', translate: 'F2' },
    { keyCode: '114', functionType:'Singlekey', value: 'F3',hid:'0x3c', translate: 'F3' },
    { keyCode: '115', functionType:'Singlekey', value: 'F4',hid:'0x3d', translate: 'F4' },
    { keyCode: '116', functionType:'Singlekey', value: 'F5',hid:'0x3e', translate: 'F5' },
    { keyCode: '117', functionType:'Singlekey', value: 'F6',hid:'0x3f', translate: 'F6' },
    { keyCode: '118', functionType:'Singlekey', value: 'F7',hid:'0x40', translate: 'F7' },
    { keyCode: '119', functionType:'Singlekey', value: 'F8',hid:'0x41', translate: 'F8' },
    { keyCode: '120', functionType:'Singlekey', value: 'F9',hid:'0x42', translate: 'F9' },
    { keyCode: '121', functionType:'Singlekey', value: 'F10',hid:'0x43', translate: 'F10' },
    { keyCode: '122', functionType:'Singlekey', value: 'F11',hid:'0x44', translate: 'F11' },
    { keyCode: '123', functionType:'Singlekey', value: 'F12',hid:'0x45', translate: 'F12' },
    { keyCode: '145', functionType:'Singlekey', value: 'Scroll Lock',hid:'0x47', translate: 'Scroll Lock' },
    { keyCode: '186', functionType:'Singlekey', value: ';',hid:'0x33', translate: ';' },
    { keyCode: '187', functionType:'Singlekey', value: '=',hid:'0x2e', translate: '=' },
    { keyCode: '188', functionType:'Singlekey', value: ',',hid:'0x36', translate: ',' },
    { keyCode: '189', functionType:'Singlekey', value: '-',hid:'0x2d', translate: '-' },
    { keyCode: '190', functionType:'Singlekey', value: 'dot',hid:'0x37', translate: 'dot' },
    { keyCode: '191', functionType:'Singlekey', value: '/',hid:'0x38', translate: '/' },
    { keyCode: '192', functionType:'Singlekey', value: '~',hid:'0x35', translate: '~' },
    { keyCode: '219', functionType:'Singlekey', value: '[',hid:'0x2f', translate: '[' },
    { keyCode: '220', functionType:'Singlekey', value: '|',hid:'0x31', translate: '|' },
    { keyCode: '221', functionType:'Singlekey', value: ']',hid:'0x30', translate: ']' },
    { keyCode: '222', functionType:'Singlekey', value: "'",hid:'0x34', translate: "'" },
    { keyCode: 'Multimedia_Fun_0', functionType:'Multimedia', value: 'Media Player',hid:'0x00',  translate: 'Media Player' },
    { keyCode: 'Multimedia_Fun_1', functionType:'Multimedia', value: 'Play/Pause',hid:'0x01',  translate: 'Play/Pause' },
    { keyCode: 'Multimedia_Fun_2', functionType:'Multimedia', value: 'Next',hid:'0x07',  translate: 'Next' },
    { keyCode: 'Multimedia_Fun_3', functionType:'Multimedia', value: 'Previous',hid:'0x06',  translate: 'Previous' },
    { keyCode: 'Multimedia_Fun_4', functionType:'Multimedia', value: 'Stop',hid:'0x05',  translate: 'Stop' },
    { keyCode: 'Multimedia_Fun_5', functionType:'Multimedia', value: 'Mute',hid:'0x02',  translate: 'Mute' },
    { keyCode: 'Multimedia_Fun_6', functionType:'Multimedia', value: 'Volume up',hid:'0x03',  translate: 'Volume up' },
    { keyCode: 'Multimedia_Fun_7', functionType:'Multimedia', value: 'Volume down',hid:'0x04',  translate: 'Volume down' },
    { keyCode: 'Multimedia_Fun_8', functionType:'Multimedia', value: 'Next track',hid:'0x07',  translate: 'Next trac' },
    { keyCode: 'Multimedia_Fun_9', functionType:'Multimedia', value: 'Previoustrack',hid:'0x06',  translate: 'Previoustrack', },
    { keyCode: 'KEYBOARD_Fun_10', functionType:'KEYBOARD', value: 'Profilecycleup',hid:'0x899',  translate: 'Profilecycleup', },
    { keyCode: 'KEYBOARD_Fun_11', functionType:'KEYBOARD', value: 'Profilecycledown',hid:'0x898',  translate: 'Profilecycledown', },
    { keyCode: 'KEYBOARD_Fun_12', functionType:'KEYBOARD', value: 'Layercycleup',hid:'0x897',  translate: 'Layercycleup' },
    { keyCode: 'KEYBOARD_Fun_13', functionType:'KEYBOARD', value: 'Layercycledown',hid:'0x896',  translate: 'Layercycledown', },
    { keyCode: 'MOUSE_Fun_14', functionType:'MOUSE', value: 'Leftbutton',hid:'0x895',  translate: 'Leftbutton' },
    { keyCode: 'MOUSE_Fun_15', functionType:'MOUSE', value: 'Rightbutton',hid:'0x894',  translate: 'Rightbutton' },
    { keyCode: 'MOUSE_Fun_16', functionType:'MOUSE', value: 'Middlebutton',hid:'0x893',  translate: 'Middlebutton' },
    { keyCode: 'MOUSE_Fun_17', functionType:'MOUSE', value: 'Forward',hid:'0x892',  translate: 'Forward' },
    { keyCode: 'MOUSE_Fun_18', functionType:'MOUSE', value: 'Back',hid:'0x891',  translate: 'Back' },
    { keyCode: 'MOUSE_Fun_19', functionType:'MOUSE', value: 'Scrollup',hid:'0x890',  translate: 'Scrollup' },
    { keyCode: 'MOUSE_Fun_20', functionType:'MOUSE', value: 'Scrolldown',hid:'0x799',  translate: 'Scrolldown' },
    { keyCode: 'MOUSE_Fun_21', functionType:'MOUSE', value: 'Profilecycleup',hid:'0x798',  translate: 'Profilecycleup' },
    { keyCode: 'MOUSE_Fun_22', functionType:'MOUSE', value: 'Profilecycledown',hid:'0x797',  translate: 'Profilecycledown' },
    { keyCode: 'MOUSE_Fun_23', functionType:'MOUSE', value: 'Batterystatuscheck',hid:'0x796',  translate: 'Batterystatuscheck', },
    { keyCode: 'LaunchProgram', functionType:'LaunchProgram', value: 'LaunchProgram',hid:'0x795',  translate: 'LaunchProgram' },
    { keyCode: 'LaunchWebsite', functionType:'LaunchProgram', value: 'LaunchWebsite',hid:'0x794',  translate: 'LaunchWebsite' },
    { keyCode: 'Shortcuts_Fun_25', functionType:'Shortcuts', value: 'Email',hid:'0x11',  translate: 'Email' },
    { keyCode: 'Shortcuts_Fun_26', functionType:'Shortcuts', value: 'Calculator',hid:'0x10',  translate: 'Calculator' },
    { keyCode: 'Shortcuts_Fun_27', functionType:'Shortcuts', value: 'My Computer',hid:'0x0f',  translate: 'My Computer' },
    { keyCode: 'Shortcuts_Fun_28', functionType:'Shortcuts', value: 'Explorer',hid:'0x0f',  translate: 'Explorer' },
    { keyCode: 'Shortcuts_Fun_29', functionType:'Shortcuts', value: 'WWW Home',hid:'0x08',  translate: 'WWW Home' },
    { keyCode: 'Shortcuts_Fun_30', functionType:'Shortcuts', value: 'WWW Refresh',hid:'0x09',  translate: 'WWW Refresh' },
    { keyCode: 'Shortcuts_Fun_31', functionType:'Shortcuts', value: 'WWW Stop',hid:'0x0a',  translate: 'WWW Stop' },
    { keyCode: 'Shortcuts_Fun_32', functionType:'Shortcuts', value: 'WWW Back',hid:'0x0b',  translate: 'WWW Back' },
    { keyCode: 'Shortcuts_Fun_33', functionType:'Shortcuts', value: 'WWW Forward',hid:'0x0c',  translate: 'WWW Forward' },
    { keyCode: 'Shortcuts_Fun_34', functionType:'Shortcuts', value: 'WWW Search',hid:'0x0e',  translate: 'WWW Search' },
    { keyCode: 'MacroFunction', functionType:'MacroFunction', value: 'MacroFunction',hid:'0x783',  translate: 'MacroFunction' },
    { keyCode: 'ScrollWheel', functionType:'ScrollWheel', value: 'ScrollWheel',hid:'0x782',  translate: 'ScrollWheel' },
    { keyCode: 'Custom_Fnkey', functionType:'Custom_Fnkey', value: 'FN',hid:'0x781',  translate: 'FN' },
    { keyCode: '0', functionType:'Singlekey', value: 'Left Click',hid:'0x780', translate: 'Left Click' },
    { keyCode: '1', functionType:'Singlekey', value: 'Scroll Click',hid:'0x779',  translate: 'Scroll Click' },
    { keyCode: '2', functionType:'Singlekey', value: 'Right Click',hid:'0x778',  translate: 'Right Click' },
    { keyCode: '3', functionType:'Singlekey', value: 'Back',hid:'0x777',  translate: 'Back' },
    { keyCode: '4',functionType:'Singlekey', value: 'Forward',hid:'0x776',  translate: 'Forward' },
    { keyCode: 'Disable_Fun35',functionType:'Disable', value: 'Disable',hid:'0x776',  translate: 'Disable' },

]

exports.KeyMapping = KeyMapping
exports.MouseMapping = MouseMapping
exports.MediaMapping = MediaMapping
exports.WindowsMapping = WindowsMapping
exports.AllFunctionMapping = AllFunctionMapping
exports.Shortcuts_WindowsMapping = Shortcuts_WindowsMapping

function ProfileDefault() {
    var Profile_Info_Default = {
        //ProfileID:1,
        MousePerformance: {
            iStage: 1,
            iXYSync: 2,
            iPollingRate: 500,
            iCalibration: 1,
        },
        MouseLighting: {
            Amplitude: 2500,
            Angle: 1,
            bQuickEffect: false,
            ColorNumber: 5,
            Decay: 50,
            Fire: 5,
            iBrightness: 50,
            iEffect: 1,
            iSpeed: 50,
            Width: 3,
        },
        MouseBtnList: [
            { id: 1, group: 1, function: 1, name: 'Left button' },
            { id: 2, group: 1, function: 2, name: 'Right button' },
            { id: 3, group: 1, function: 3, name: 'Middle button' },
            { id: 4, group: 4, function: 1, name: 'Lighting effect switch' },
            { id: 5, group: 1, function: 10, name: 'DPI increase loop' },
            { id: 6, group: 1, function: 4, name: 'Forward button' },
            { id: 7, group: 1, function: 5, name: 'Backward button' },
            { id: 8, group: 1, function: 13, name: 'Squeeze' },
        ],
    }
    return Profile_Info_Default
}
exports.ProfileDefault = ProfileDefault

var CountryCode = [
    { code: 'AF', value: 'Afghanistan' },
    { code: 'AX', value: 'Åland Islands' },
    { code: 'AL', value: 'Albania' },
    { code: 'DZ', value: 'Algeria' },
    { code: 'AS', value: 'American Samoa' },
    { code: 'AD', value: 'Andorra' },
    { code: 'AO', value: 'Angola' },
    { code: 'AI', value: 'Anguilla' },
    { code: 'AQ', value: 'Antarctica' },
    { code: 'AG', value: 'Antigua and Barbuda' },
    { code: 'AR', value: 'Argentina' },
    { code: 'AM', value: 'Armenia' },
    { code: 'AW', value: 'Aruba' },
    { code: 'AU', value: 'Australia' },
    { code: 'AT', value: 'Austria' },
    { code: 'AZ', value: 'Azerbaijan' },
    { code: 'BS', value: 'Bahamas' },
    { code: 'BH', value: 'Bahrain' },
    { code: 'BD', value: 'Bangladesh' },
    { code: 'BB', value: 'Barbados' },
    { code: 'BY', value: 'Belarus' },
    { code: 'BE', value: 'Belgium' },
    { code: 'BZ', value: 'Belize' },
    { code: 'BJ', value: 'Benin' },
    { code: 'BM', value: 'Bermuda' },
    { code: 'BT', value: 'Bhutan' },
    { code: 'BO', value: 'Bolivia, Plurinational State of' },
    { code: 'BQ', value: 'Bonaire, Sint Eustatius and Saba' },
    { code: 'BA', value: 'Bosnia and Herzegovina' },
    { code: 'BW', value: 'Botswana' },
    { code: 'BV', value: 'Bouvet Island' },
    { code: 'BR', value: 'Brazil' },
    { code: 'IO', value: 'British Indian Ocean Territory' },
    { code: 'BN', value: 'Brunei Darussalam' },
    { code: 'BG', value: 'Bulgaria' },
    { code: 'BF', value: 'Burkina Faso' },
    { code: 'BI', value: 'Burundi' },
    { code: 'KH', value: 'Cambodia' },
    { code: 'CM', value: 'Cameroon' },
    { code: 'CA', value: 'Canada' },
    { code: 'CV', value: 'Cape Verde' },
    { code: 'KY', value: 'Cayman Islands' },
    { code: 'CF', value: 'Central African Republic' },
    { code: 'TD', value: 'Chad' },
    { code: 'CL', value: 'Chile' },
    { code: 'CN', value: 'China' },
    { code: 'CX', value: 'Christmas Island' },
    { code: 'CC', value: 'Cocos (Keeling) Islands' },
    { code: 'CO', value: 'Colombia' },
    { code: 'KM', value: 'Comoros' },
    { code: 'CG', value: 'Congo' },
    { code: 'CD', value: 'Congo, the Democratic Republic of the' },
    { code: 'CK', value: 'Cook Islands' },
    { code: 'CR', value: 'Costa Rica' },
    { code: 'CI', value: "Côte d'Ivoire" },
    { code: 'HR', value: 'Croatia' },
    { code: 'CU', value: 'Cuba' },
    { code: 'CW', value: 'Curaçao' },
    { code: 'CY', value: 'Cyprus' },
    { code: 'CZ', value: 'Czech Republic' },
    { code: 'DK', value: 'Denmark' },
    { code: 'DJ', value: 'Djibouti' },
    { code: 'DM', value: 'Dominica' },
    { code: 'DO', value: 'Dominican Republic' },
    { code: 'EC', value: 'Ecuador' },
    { code: 'EG', value: 'Egypt' },
    { code: 'SV', value: 'El Salvador' },
    { code: 'GQ', value: 'Equatorial Guinea' },
    { code: 'ER', value: 'Eritrea' },
    { code: 'EE', value: 'Estonia' },
    { code: 'ET', value: 'Ethiopia' },
    { code: 'FK', value: 'Falkland Islands (Malvinas)' },
    { code: 'FO', value: 'Faroe Islands' },
    { code: 'FJ', value: 'Fiji' },
    { code: 'FI', value: 'Finland' },
    { code: 'FR', value: 'France' },
    { code: 'GF', value: 'French Guiana' },
    { code: 'PF', value: 'French Polynesia' },
    { code: 'TF', value: 'French Southern Territories' },
    { code: 'GA', value: 'Gabon' },
    { code: 'GM', value: 'Gambia' },
    { code: 'GE', value: 'Georgia' },
    { code: 'DE', value: 'Germany' },
    { code: 'GH', value: 'Ghana' },
    { code: 'GI', value: 'Gibraltar' },
    { code: 'GR', value: 'Greece' },
    { code: 'GL', value: 'Greenland' },
    { code: 'GD', value: 'Grenada' },
    { code: 'GP', value: 'Guadeloupe' },
    { code: 'GU', value: 'Guam' },
    { code: 'GT', value: 'Guatemala' },
    { code: 'GG', value: 'Guernsey' },
    { code: 'GN', value: 'Guinea' },
    { code: 'GW', value: 'Guinea-Bissau' },
    { code: 'GY', value: 'Guyana' },
    { code: 'HT', value: 'Haiti' },
    { code: 'HM', value: 'Heard Island and McDonald Islands' },
    { code: 'VA', value: 'Holy See (Vatican City State)' },
    { code: 'HN', value: 'Honduras' },
    { code: 'HK', value: 'Hong Kong' },
    { code: 'HU', value: 'Hungary' },
    { code: 'IS', value: 'Iceland' },
    { code: 'IN', value: 'India' },
    { code: 'ID', value: 'Indonesia' },
    { code: 'IR', value: 'Iran, Islamic Republic of' },
    { code: 'IQ', value: 'Iraq' },
    { code: 'IE', value: 'Ireland' },
    { code: 'IM', value: 'Isle of Man' },
    { code: 'IL', value: 'Israel' },
    { code: 'IT', value: 'Italy' },
    { code: 'JM', value: 'Jamaica' },
    { code: 'JP', value: 'Japan' },
    { code: 'JE', value: 'Jersey' },
    { code: 'JO', value: 'Jordan' },
    { code: 'KZ', value: 'Kazakhstan' },
    { code: 'KE', value: 'Kenya' },
    { code: 'KI', value: 'Kiribati' },
    { code: 'KP', value: "Korea, Democratic People's Republic of" },
    { code: 'KR', value: 'Korea, Republic of' },
    { code: 'KW', value: 'Kuwait' },
    { code: 'KG', value: 'Kyrgyzstan' },
    { code: 'LA', value: "Lao People's Democratic Republic" },
    { code: 'LV', value: 'Latvia' },
    { code: 'LB', value: 'Lebanon' },
    { code: 'LS', value: 'Lesotho' },
    { code: 'LR', value: 'Liberia' },
    { code: 'LY', value: 'Libya' },
    { code: 'LI', value: 'Liechtenstein' },
    { code: 'LT', value: 'Lithuania' },
    { code: 'LU', value: 'Luxembourg' },
    { code: 'MO', value: 'Macao' },
    { code: 'MK', value: 'Macedonia, the former Yugoslav Republic of' },
    { code: 'MG', value: 'Madagascar' },
    { code: 'MW', value: 'Malawi' },
    { code: 'MY', value: 'Malaysia' },
    { code: 'MV', value: 'Maldives' },
    { code: 'ML', value: 'Mali' },
    { code: 'MT', value: 'Malta' },
    { code: 'MH', value: 'Marshall Islands' },
    { code: 'MQ', value: 'Martinique' },
    { code: 'MR', value: 'Mauritania' },
    { code: 'MU', value: 'Mauritius' },
    { code: 'YT', value: 'Mayotte' },
    { code: 'MX', value: 'Mexico' },
    { code: 'FM', value: 'Micronesia, Federated States of' },
    { code: 'MD', value: 'Moldova, Republic of' },
    { code: 'MC', value: 'Monaco' },
    { code: 'MN', value: 'Mongolia' },
    { code: 'ME', value: 'Montenegro' },
    { code: 'MS', value: 'Montserrat' },
    { code: 'MA', value: 'Morocco' },
    { code: 'MZ', value: 'Mozambique' },
    { code: 'MM', value: 'Myanmar' },
    { code: 'NA', value: 'Namibia' },
    { code: 'NR', value: 'Nauru' },
    { code: 'NP', value: 'Nepal' },
    { code: 'NL', value: 'Netherlands' },
    { code: 'NC', value: 'New Caledonia' },
    { code: 'NZ', value: 'New Zealand' },
    { code: 'NI', value: 'Nicaragua' },
    { code: 'NE', value: 'Niger' },
    { code: 'NG', value: 'Nigeria' },
    { code: 'NU', value: 'Niue' },
    { code: 'NF', value: 'Norfolk Island' },
    { code: 'MP', value: 'Northern Mariana Islands' },
    { code: 'NO', value: 'Norway' },
    { code: 'OM', value: 'Oman' },
    { code: 'PK', value: 'Pakistan' },
    { code: 'PW', value: 'Palau' },
    { code: 'PS', value: 'Palestinian Territory, Occupied' },
    { code: 'PA', value: 'Panama' },
    { code: 'PG', value: 'Papua New Guinea' },
    { code: 'PY', value: 'Paraguay' },
    { code: 'PE', value: 'Peru' },
    { code: 'PH', value: 'Philippines' },
    { code: 'PN', value: 'Pitcairn' },
    { code: 'PL', value: 'Poland' },
    { code: 'PT', value: 'Portugal' },
    { code: 'PR', value: 'Puerto Rico' },
    { code: 'QA', value: 'Qatar' },
    { code: 'RE', value: 'Réunion' },
    { code: 'RO', value: 'Romania' },
    { code: 'RU', value: 'Russian Federation' },
    { code: 'RW', value: 'Rwanda' },
    { code: 'BL', value: 'Saint Barthélemy' },
    { code: 'SH', value: 'Saint Helena, Ascension and Tristan da Cunha' },
    { code: 'KN', value: 'Saint Kitts and Nevis' },
    { code: 'LC', value: 'Saint Lucia' },
    { code: 'MF', value: 'Saint Martin (French part)' },
    { code: 'PM', value: 'Saint Pierre and Miquelon' },
    { code: 'VC', value: 'Saint Vincent and the Grenadines' },
    { code: 'WS', value: 'Samoa' },
    { code: 'SM', value: 'San Marino' },
    { code: 'ST', value: 'Sao Tome and Principe' },
    { code: 'SA', value: 'Saudi Arabia' },
    { code: 'SN', value: 'Senegal' },
    { code: 'RS', value: 'Serbia' },
    { code: 'SC', value: 'Seychelles' },
    { code: 'SL', value: 'Sierra Leone' },
    { code: 'SG', value: 'Singapore' },
    { code: 'SX', value: 'Sint Maarten (Dutch part)' },
    { code: 'SK', value: 'Slovakia' },
    { code: 'SI', value: 'Slovenia' },
    { code: 'SB', value: 'Solomon Islands' },
    { code: 'SO', value: 'Somalia' },
    { code: 'ZA', value: 'South Africa' },
    { code: 'GS', value: 'South Georgia and the South Sandwich Islands' },
    { code: 'SS', value: 'South Sudan' },
    { code: 'ES', value: 'Spain' },
    { code: 'LK', value: 'Sri Lanka' },
    { code: 'SD', value: 'Sudan' },
    { code: 'SR', value: 'Suriname' },
    { code: 'SJ', value: 'Svalbard and Jan Mayen' },
    { code: 'SZ', value: 'Swaziland' },
    { code: 'SE', value: 'Sweden' },
    { code: 'CH', value: 'Switzerland' },
    { code: 'SY', value: 'Syrian Arab Republic' },
    { code: 'TW', value: 'Taiwan, Province of China' },
    { code: 'TJ', value: 'Tajikistan' },
    { code: 'TZ', value: 'Tanzania, United Republic of' },
    { code: 'TH', value: 'Thailand' },
    { code: 'TL', value: 'Timor-Leste' },
    { code: 'TG', value: 'Togo' },
    { code: 'TK', value: 'Tokelau' },
    { code: 'TO', value: 'Tonga' },
    { code: 'TT', value: 'Trinidad and Tobago' },
    { code: 'TN', value: 'Tunisia' },
    { code: 'TR', value: 'Turkey' },
    { code: 'TM', value: 'Turkmenistan' },
    { code: 'TC', value: 'Turks and Caicos Islands' },
    { code: 'TV', value: 'Tuvalu' },
    { code: 'UG', value: 'Uganda' },
    { code: 'UA', value: 'Ukraine' },
    { code: 'AE', value: 'United Arab Emirates' },
    { code: 'GB', value: 'United Kingdom' },
    { code: 'US', value: 'United States' },
    { code: 'UM', value: 'United States Minor Outlying Islands' },
    { code: 'UY', value: 'Uruguay' },
    { code: 'UZ', value: 'Uzbekistan' },
    { code: 'VU', value: 'Vanuatu' },
    { code: 'VE', value: 'Venezuela, Bolivarian Republic of' },
    { code: 'VN', value: 'Viet Nam' },
    { code: 'VG', value: 'Virgin Islands, British' },
    { code: 'VI', value: 'Virgin Islands, U.S.' },
    { code: 'WF', value: 'Wallis and Futuna' },
    { code: 'EH', value: 'Western Sahara' },
    { code: 'YE', value: 'Yemen' },
    { code: 'ZM', value: 'Zambia' },
    { code: 'ZW', value: 'Zimbabwe' },
]

exports.CountryCode = CountryCode
