export const KeyMapping = [
    { "keyCode": "65", "functionType": "Singlekey", "value": "A", "hid": 4, "translate": "A", "code": "KeyA" },
    { "keyCode": "66", "functionType": "Singlekey", "value": "B", "hid": 5, "translate": "B", "code": "KeyB" },
    { "keyCode": "67", "functionType": "Singlekey", "value": "C", "hid": 6, "translate": "C", "code": "KeyC" },
    { "keyCode": "68", "functionType": "Singlekey", "value": "D", "hid": 7, "translate": "D", "code": "KeyD" },
    { "keyCode": "69", "functionType": "Singlekey", "value": "E", "hid": 8, "translate": "E", "code": "KeyE" },
    { "keyCode": "70", "functionType": "Singlekey", "value": "F", "hid": 9, "translate": "F", "code": "KeyF" },
    { "keyCode": "71", "functionType": "Singlekey", "value": "G", "hid": 10, "translate": "G", "code": "KeyG" },
    { "keyCode": "72", "functionType": "Singlekey", "value": "H", "hid": 11, "translate": "H", "code": "KeyH" },
    { "keyCode": "73", "functionType": "Singlekey", "value": "I", "hid": 12, "translate": "I", "code": "KeyI" },
    { "keyCode": "74", "functionType": "Singlekey", "value": "J", "hid": 13, "translate": "J", "code": "KeyJ" },
    { "keyCode": "75", "functionType": "Singlekey", "value": "K", "hid": 14, "translate": "K", "code": "KeyK" },
    { "keyCode": "76", "functionType": "Singlekey", "value": "L", "hid": 15, "translate": "L", "code": "KeyL" },
    { "keyCode": "77", "functionType": "Singlekey", "value": "M", "hid": 16, "translate": "M", "code": "KeyM" },
    { "keyCode": "78", "functionType": "Singlekey", "value": "N", "hid": 17, "translate": "N", "code": "KeyN" },
    { "keyCode": "79", "functionType": "Singlekey", "value": "O", "hid": 18, "translate": "O", "code": "KeyO" },
    { "keyCode": "80", "functionType": "Singlekey", "value": "P", "hid": 19, "translate": "P", "code": "KeyP" },
    { "keyCode": "81", "functionType": "Singlekey", "value": "Q", "hid": 20, "translate": "Q", "code": "KeyQ" },
    { "keyCode": "82", "functionType": "Singlekey", "value": "R", "hid": 21, "translate": "R", "code": "KeyR" },
    { "keyCode": "83", "functionType": "Singlekey", "value": "S", "hid": 22, "translate": "S", "code": "KeyS" },
    { "keyCode": "84", "functionType": "Singlekey", "value": "T", "hid": 23, "translate": "T", "code": "KeyT" },
    { "keyCode": "85", "functionType": "Singlekey", "value": "U", "hid": 24, "translate": "U", "code": "KeyU" },
    { "keyCode": "86", "functionType": "Singlekey", "value": "V", "hid": 25, "translate": "V", "code": "KeyV" },
    { "keyCode": "87", "functionType": "Singlekey", "value": "W", "hid": 26, "translate": "W", "code": "KeyW" },
    { "keyCode": "88", "functionType": "Singlekey", "value": "X", "hid": 27, "translate": "X", "code": "KeyX" },
    { "keyCode": "89", "functionType": "Singlekey", "value": "Y", "hid": 28, "translate": "Y", "code": "KeyY" },
    { "keyCode": "90", "functionType": "Singlekey", "value": "Z", "hid": 29, "translate": "Z", "code": "KeyZ" },
    { "keyCode": "48", "functionType": "Singlekey", "value": "0", "hid": 39, "translate": "0", "code": "Digit0" },
    { "keyCode": "49", "functionType": "Singlekey", "value": "1", "hid": 30, "translate": "1", "code": "Digit1" },
    { "keyCode": "50", "functionType": "Singlekey", "value": "2", "hid": 31, "translate": "2", "code": "Digit2" },
    { "keyCode": "51", "functionType": "Singlekey", "value": "3", "hid": 32, "translate": "3", "code": "Digit3" },
    { "keyCode": "52", "functionType": "Singlekey", "value": "4", "hid": 33, "translate": "4", "code": "Digit4" },
    { "keyCode": "53", "functionType": "Singlekey", "value": "5", "hid": 34, "translate": "5", "code": "Digit5" },
    { "keyCode": "54", "functionType": "Singlekey", "value": "6", "hid": 35, "translate": "6", "code": "Digit6" },
    { "keyCode": "55", "functionType": "Singlekey", "value": "7", "hid": 36, "translate": "7", "code": "Digit7" },
    { "keyCode": "56", "functionType": "Singlekey", "value": "8", "hid": 37, "translate": "8", "code": "Digit8" },
    { "keyCode": "57", "functionType": "Singlekey", "value": "9", "hid": 38, "translate": "9", "code": "Digit9" },
    { "keyCode": "8", "functionType": "Singlekey", "value": "Backspace", "hid": 42, "translate": "Backspace", "code": "Backspace" },
    { "keyCode": "9", "functionType": "Singlekey", "value": "Tab", "hid": 43, "translate": "Tab", "code": "Tab" },
    { "keyCode": "144", "functionType": "Singlekey", "value": "Num Lock", "hid": 83, "translate": "Num Lock", "code": "NumLock" },
    { "keyCode": "13", "functionType": "Singlekey", "value": "Enter", "hid": 40, "translate": "Enter", "code": "Enter" },
    { "keyCode": "16", "functionType": "Singlekey", "value": "Shift", "hid": 225, "Modifier": 0x02, "translate": "Shift", "code": "ShiftRight" },
    { "keyCode": "17", "functionType": "Singlekey", "value": "Ctrl", "hid": 224, "Modifier": 0x01, "translate": "Ctrl", "code": "ControlLeft" },
    { "keyCode": "18", "functionType": "Singlekey", "value": "Alt", "hid": 226, "Modifier": 0x04, "translate": "Alt", "code": "AltRight" },
    { "keyCode": "19", "functionType": "Singlekey", "value": "Break", "hid": 72, "translate": "Break", "code": "Pause" },
    { "keyCode": "20", "functionType": "Singlekey", "value": "CapsLock", "hid": 57, "translate": "CapsLock", "code": "CapsLock" },
    { "keyCode": "27", "functionType": "Singlekey", "value": "Esc", "hid": 41, "translate": "Esc", "code": "Escape" },
    { "keyCode": "32", "functionType": "Singlekey", "value": "Space", "hid": 44, "translate": "Space", "code": "Space" },
    { "keyCode": "33", "functionType": "Singlekey", "value": "PageUp", "hid": 75, "translate": "PageUp", "code": "PageUp" },
    { "keyCode": "34", "functionType": "Singlekey", "value": "PageDown", "hid": 78, "translate": "PageDown", "code": "PageDown" },
    { "keyCode": "35", "functionType": "Singlekey", "value": "End", "hid": 77, "translate": "End", "code": "End" },
    { "keyCode": "36", "functionType": "Singlekey", "value": "Home", "hid": 74, "translate": "Home", "code": "Home" },
    { "keyCode": "37", "functionType": "Singlekey", "value": "Left", "hid": 80, "translate": "Left", "code": "ArrowLeft" },
    { "keyCode": "38", "functionType": "Singlekey", "value": "Up", "hid": 82, "translate": "Up", "code": "ArrowUp" },
    { "keyCode": "39", "functionType": "Singlekey", "value": "Right", "hid": 79, "translate": "Right", "code": "ArrowRight" },
    { "keyCode": "40", "functionType": "Singlekey", "value": "Down", "hid": 81, "translate": "Down", "code": "ArrowDown" },
    { "keyCode": "44", "functionType": "Singlekey", "value": "PrintScreen", "hid": "0x46", "translate": "PrintScreen", "code": "PrintScreen" },
    { "keyCode": "45", "functionType": "Singlekey", "value": "Insert", "hid": 73, "translate": "Insert", "code": "Insert" },
    { "keyCode": "46", "functionType": "Singlekey", "value": "Delete", "hid": 76, "translate": "Delete", "code": "Delete" },
    { "keyCode": "91", "functionType": "Singlekey", "value": "Left Win", "hid": 227, "Modifier": 0x08, "translate": "Left Win", "code": "MetaLeft" },
    { "keyCode": "92", "functionType": "Singlekey", "value": "Right Win", "hid": 231, "Modifier": 0x80, "translate": "Right Win", "code": "MetaRight" },
    { "keyCode": "93", "functionType": "Singlekey", "value": "Menu", "hid": 101, "translate": "Menu", "code": "ContextMenu" },
    { "keyCode": "106", "functionType": "Singlekey", "value": "*", "hid": 85, "translate": "*", "code": "NumpadMultiply" },
    { "keyCode": "107", "functionType": "Singlekey", "value": "+", "hid": 87, "translate": "+", "code": "NumpadAdd" },
    { "keyCode": "109", "functionType": "Singlekey", "value": "-", "hid": 86, "translate": "-", "code": "NumpadSubtract" },
    { "keyCode": "110", "functionType": "Singlekey", "value": ".", "hid": 0x63, "translate": ".", "code": "NumpadDecimal" },
    { "keyCode": "111", "functionType": "Singlekey", "value": "/", "hid": 84, "translate": "/", "code": "NumpadDivide" },
    { "keyCode": "112", "functionType": "Singlekey", "value": "F1", "hid": 58, "translate": "F1", "code": "F1" },
    { "keyCode": "113", "functionType": "Singlekey", "value": "F2", "hid": 59, "translate": "F2", "code": "F2" },
    { "keyCode": "114", "functionType": "Singlekey", "value": "F3", "hid": 60, "translate": "F3", "code": "F3" },
    { "keyCode": "115", "functionType": "Singlekey", "value": "F4", "hid": 61, "translate": "F4", "code": "F4" },
    { "keyCode": "116", "functionType": "Singlekey", "value": "F5", "hid": 62, "translate": "F5", "code": "F5" },
    { "keyCode": "117", "functionType": "Singlekey", "value": "F6", "hid": 63, "translate": "F6", "code": "F6" },
    { "keyCode": "118", "functionType": "Singlekey", "value": "F7", "hid": 64, "translate": "F7", "code": "F7" },
    { "keyCode": "119", "functionType": "Singlekey", "value": "F8", "hid": 65, "translate": "F8", "code": "F8" },
    { "keyCode": "120", "functionType": "Singlekey", "value": "F9", "hid": 66, "translate": "F9", "code": "F9" },
    { "keyCode": "121", "functionType": "Singlekey", "value": "F10", "hid": 67, "translate": "F10", "code": "F10" },
    { "keyCode": "122", "functionType": "Singlekey", "value": "F11", "hid": 68, "translate": "F11", "code": "F11" },
    { "keyCode": "123", "functionType": "Singlekey", "value": "F12", "hid": 69, "translate": "F12", "code": "F12" },
    { "keyCode": "145", "functionType": "Singlekey", "value": "Scroll Lock", "hid": 71, "translate": "Scroll Lock", "code": "ScrollLock" },
    { "keyCode": "186", "functionType": "Singlekey", "value": ";", "hid": 51, "translate": ";", "code": "Semicolon" },
    { "keyCode": "187", "functionType": "Singlekey", "value": "=", "hid": 46, "translate": "=", "code": "Equal" },
    { "keyCode": "188", "functionType": "Singlekey", "value": ",", "hid": 54, "translate": ",", "code": "Comma" },
    { "keyCode": "189", "functionType": "Singlekey", "value": "-", "hid": 45, "translate": "-", "code": "Minus" },
    { "keyCode": "190", "functionType": "Singlekey", "value": "dot", "hid": 55, "translate": "dot", "code": "Period" },
    { "keyCode": "191", "functionType": "Singlekey", "value": "/", "hid": 56, "translate": "/", "code": "Slash" },
    { "keyCode": "192", "functionType": "Singlekey", "value": "~", "hid": 53, "translate": "~", "code": "Backquote" },
    { "keyCode": "219", "functionType": "Singlekey", "value": "[", "hid": 47, "translate": "[", "code": "BracketLeft" },
    { "keyCode": "220", "functionType": "Singlekey", "value": "|", "hid": 49, "translate": "|", "code": "Backslash" },
    { "keyCode": "221", "functionType": "Singlekey", "value": "]", "hid": 48, "translate": "]", "code": "BracketRight" },
    { "keyCode": "222", "functionType": "Singlekey", "value": "'", "hid": 52, "translate": "'", "code": "Quote" }

]
export const MediaMapping = [
    { keyCode: '1', value: 'None', "hid": 0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Media Player', "hid": 0x04, hidMap: [0x01, 0x83], translate: '' },
    { keyCode: '1', value: 'Play/Pause', "hid": 0x04, hidMap: [0x00, 0xcd], translate: '' },
    { keyCode: '1', value: 'Next', "hid": 0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous', "hid": 0x04, hidMap: [0x00, 0xb6], translate: '' },
    { keyCode: '1', value: 'Stop', "hid": 0x04, hidMap: [0x00, 0xb7], translate: '' },
    { keyCode: '1', value: 'Mute', "hid": 0x04, hidMap: [0x00, 0xe2], translate: '' },
    { keyCode: '1', value: 'Volume up', "hid": 0x04, hidMap: [0x00, 0xe9], translate: '' },
    { keyCode: '1', value: 'Volume down', "hid": 0x04, hidMap: [0x00, 0xea], translate: '' },
    { keyCode: '1', value: 'Next track', "hid": 0x04, hidMap: [0x00, 0xb5], translate: '' },
    { keyCode: '1', value: 'Previous track', "hid": 0x04, hidMap: [0x00, 0xb6], translate: '' },
]
export const WindowsMapping = [
    { keyCode: '1', value: 'None', "hid": 0x04, hidMap: [0x00, 0x00], translate: '' },
    { keyCode: '1', value: 'Email', "hid": 0x04, hidMap: [0x01, 0x8a], translate: '' },
    { keyCode: '1', value: 'Calculator', "hid": 0x04, hidMap: [0x01, 0x92], translate: '' },
    { keyCode: '1', value: 'My Computer', "hid": 0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'Explorer', "hid": 0x04, hidMap: [0x01, 0x94], translate: '' },
    { keyCode: '1', value: 'WWW Home', "hid": 0x04, hidMap: [0x02, 0x23], translate: '' },
    { keyCode: '1', value: 'WWW Refresh', "hid": 0x04, hidMap: [0x02, 0x27], translate: '' },
    { keyCode: '1', value: 'WWW Stop', "hid": 0x04, hidMap: [0x02, 0x26], translate: '' },
    { keyCode: '1', value: 'WWW Back', "hid": 0x04, hidMap: [0x02, 0x24], translate: '' },
    { keyCode: '1', value: 'WWW Forward', "hid": 0x04, hidMap: [0x02, 0x25], translate: '' },
    { keyCode: '1', value: 'WWW Search', "hid": 0x04, hidMap: [0x02, 0x21], translate: '' },
]
export const Shortcuts_WindowsMapping = [
    { "keyCode": "Shortcuts_Fun_25", "functionType": "Shortcuts", "value": "Email", "hid": 17, "translate": "Email", "code": "Shortcuts_Fun_25" },
    { "keyCode": "Shortcuts_Fun_26", "functionType": "Shortcuts", "value": "Calculator", "hid": 16, "translate": "Calculator", "code": "Shortcuts_Fun_26" },
    { "keyCode": "Shortcuts_Fun_27", "functionType": "Shortcuts", "value": "My Computer", "hid": 15, "translate": "My Computer", "code": "Shortcuts_Fun_27" },
    { "keyCode": "Shortcuts_Fun_28", "functionType": "Shortcuts", "value": "Explorer", "hid": 15, "translate": "Explorer", "code": "Shortcuts_Fun_28" },
    { "keyCode": "Shortcuts_Fun_29", "functionType": "Shortcuts", "value": "WWW Home", "hid": 8, "translate": "WWW Home", "code": "Shortcuts_Fun_29" },
    { "keyCode": "Shortcuts_Fun_30", "functionType": "Shortcuts", "value": "WWW Refresh", "hid": 9, "translate": "WWW Refresh", "code": "Shortcuts_Fun_30" },
    { "keyCode": "Shortcuts_Fun_31", "functionType": "Shortcuts", "value": "WWW Stop", "hid": 10, "translate": "WWW Stop", "code": "Shortcuts_Fun_31" },
    { "keyCode": "Shortcuts_Fun_32", "functionType": "Shortcuts", "value": "WWW Back", "hid": 11, "translate": "WWW Back", "code": "Shortcuts_Fun_32" },
    { "keyCode": "Shortcuts_Fun_33", "functionType": "Shortcuts", "value": "WWW Forward", "hid": 12, "translate": "WWW Forward", "code": "Shortcuts_Fun_33" },
    { "keyCode": "Shortcuts_Fun_34", "functionType": "Shortcuts", "value": "WWW Search", "hid": 14, "translate": "WWW Search", "code": "Shortcuts_Fun_34" },
]
export const AllFunctionMapping = [{ "keyCode": "Multimedia_Fun_0", "functionType": "Multimedia", "value": "Media Player", "hid": 0, "translate": "Media Player", "code": "Multimedia_Fun_0" },
{ "keyCode": "Multimedia_Fun_1", "functionType": "Multimedia", "value": "Play/Pause", "hid": 1, "translate": "Play/Pause", "code": "Multimedia_Fun_1" },
{ "keyCode": "Multimedia_Fun_2", "functionType": "Multimedia", "value": "Next", "hid": 7, "translate": "Next", "code": "Multimedia_Fun_2" },
{ "keyCode": "Multimedia_Fun_3", "functionType": "Multimedia", "value": "Previous", "hid": 6, "translate": "Previous", "code": "Multimedia_Fun_3" },
{ "keyCode": "Multimedia_Fun_4", "functionType": "Multimedia", "value": "Stop", "hid": 5, "translate": "Stop", "code": "Multimedia_Fun_4" },
{ "keyCode": "Multimedia_Fun_5", "functionType": "Multimedia", "value": "Mute", "hid": 2, "translate": "Mute", "code": "Multimedia_Fun_5" },
{ "keyCode": "Multimedia_Fun_6", "functionType": "Multimedia", "value": "Volume up", "hid": 3, "translate": "Volume up", "code": "Multimedia_Fun_6" },
{ "keyCode": "Multimedia_Fun_7", "functionType": "Multimedia", "value": "Volume down", "hid": 4, "translate": "Volume down", "code": "Multimedia_Fun_7" },
{ "keyCode": "Multimedia_Fun_8", "functionType": "Multimedia", "value": "Next track", "hid": 7, "translate": "Next trac", "code": "Multimedia_Fun_8" },
{ "keyCode": "Multimedia_Fun_9", "functionType": "Multimedia", "value": "Previoustrack", "hid": 6, "translate": "Previoustrack", "code": "Multimedia_Fun_9" },
{ "keyCode": "KEYBOARD_Fun_10", "functionType": "KEYBOARD", "value": "Profilecycleup", "hid": 2, "translate": "Profilecycleup", "code": "KEYBOARD_Fun_10" },
{ "keyCode": "KEYBOARD_Fun_11", "functionType": "KEYBOARD", "value": "Profilecycledown", "hid": 1, "translate": "Profilecycledown", "code": "KEYBOARD_Fun_11" },
{ "keyCode": "KEYBOARD_Fun_12", "functionType": "KEYBOARD", "value": "Layercycleup", "hid": 4, "translate": "Layercycleup", "code": "KEYBOARD_Fun_12" },
{ "keyCode": "KEYBOARD_Fun_13", "functionType": "KEYBOARD", "value": "Layercycledown", "hid": 3, "translate": "Layercycledown", "code": "KEYBOARD_Fun_13" },
{ "keyCode": "MOUSE_Fun_14", "functionType": "MOUSE", "value": "Leftbutton", "hid": 1, "translate": "Leftbutton", "code": "MOUSE_Fun_14" },
{ "keyCode": "MOUSE_Fun_15", "functionType": "MOUSE", "value": "Rightbutton", "hid": 2, "translate": "Rightbutton", "code": "MOUSE_Fun_15" },
{ "keyCode": "MOUSE_Fun_16", "functionType": "MOUSE", "value": "Middlebutton", "hid": 3, "translate": "Middlebutton", "code": "MOUSE_Fun_16" },
{ "keyCode": "MOUSE_Fun_17", "functionType": "MOUSE", "value": "Forward", "hid": 5, "translate": "Forward", "code": "MOUSE_Fun_17" },
{ "keyCode": "MOUSE_Fun_18", "functionType": "MOUSE", "value": "Back", "hid": 4, "translate": "Back", "code": "MOUSE_Fun_18" },
{ "keyCode": "MOUSE_Fun_19", "functionType": "MOUSE", "value": "Scrollup", "hid": 6, "translate": "Scrollup", "code": "MOUSE_Fun_19" },
{ "keyCode": "MOUSE_Fun_20", "functionType": "MOUSE", "value": "Scrolldown", "hid": 7, "translate": "Scrolldown", "code": "MOUSE_Fun_20" },
{ "keyCode": "MOUSE_Fun_21", "functionType": "MOUSE", "value": "Profilecycleup", "hid": 1944, "translate": "Profilecycleup", "code": "MOUSE_Fun_21" },
{ "keyCode": "MOUSE_Fun_22", "functionType": "MOUSE", "value": "Profilecycledown", "hid": 1943, "translate": "Profilecycledown", "code": "MOUSE_Fun_22" },
{ "keyCode": "MOUSE_Fun_23", "functionType": "MOUSE", "value": "Batterystatuscheck", "hid": 1942, "translate": "Batterystatuscheck", "code": "MOUSE_Fun_23" },
{ "keyCode": "LaunchProgram", "functionType": "LaunchProgram", "value": "LaunchProgram", "hid": 1941, "translate": "LaunchProgram", "code": "LaunchProgram" },
{ "keyCode": "LaunchWebsite", "functionType": "LaunchProgram", "value": "LaunchWebsite", "hid": 1940, "translate": "LaunchWebsite", "code": "LaunchWebsite" },
{ "keyCode": "Shortcuts_Fun_25", "functionType": "Shortcuts", "value": "Email", "hid": 17, "translate": "Email", "code": "Shortcuts_Fun_25" },
{ "keyCode": "Shortcuts_Fun_26", "functionType": "Shortcuts", "value": "Calculator", "hid": 16, "translate": "Calculator", "code": "Shortcuts_Fun_26" },
{ "keyCode": "Shortcuts_Fun_27", "functionType": "Shortcuts", "value": "My Computer", "hid": 15, "translate": "My Computer", "code": "Shortcuts_Fun_27" },
{ "keyCode": "Shortcuts_Fun_28", "functionType": "Shortcuts", "value": "Explorer", "hid": 15, "translate": "Explorer", "code": "Shortcuts_Fun_28" },
{ "keyCode": "Shortcuts_Fun_29", "functionType": "Shortcuts", "value": "WWW Home", "hid": 8, "translate": "WWW Home", "code": "Shortcuts_Fun_29" },
{ "keyCode": "Shortcuts_Fun_30", "functionType": "Shortcuts", "value": "WWW Refresh", "hid": 9, "translate": "WWW Refresh", "code": "Shortcuts_Fun_30" },
{ "keyCode": "Shortcuts_Fun_31", "functionType": "Shortcuts", "value": "WWW Stop", "hid": 10, "translate": "WWW Stop", "code": "Shortcuts_Fun_31" },
{ "keyCode": "Shortcuts_Fun_32", "functionType": "Shortcuts", "value": "WWW Back", "hid": 11, "translate": "WWW Back", "code": "Shortcuts_Fun_32" },
{ "keyCode": "Shortcuts_Fun_33", "functionType": "Shortcuts", "value": "WWW Forward", "hid": 12, "translate": "WWW Forward", "code": "Shortcuts_Fun_33" },
{ "keyCode": "Shortcuts_Fun_34", "functionType": "Shortcuts", "value": "WWW Search", "hid": 14, "translate": "WWW Search", "code": "Shortcuts_Fun_34" },
{ "keyCode": "Side Light", "functionType": "SideLight", "value": "Side Light", "hid": 14, "translate": "Side Light", "code": "Side Light" },
{ "keyCode": "slider", "functionType": "slider", "value": "SLIDER", "hid": 14, "translate": "slider", "code": "slider" },
{ "keyCode": "ROTARY ENCODER", "functionType": "RotaryEncoder", "value": "ROTARY ENCODER", "hid": 14, "translate": "ROTARY ENCODER", "code": "ROTARY ENCODER" },

{ "keyCode": "MacroFunction", "functionType": "MacroFunction", "value": "MacroFunction", "hid": 1923, "translate": "MacroFunction", "code": "MacroFunction" },
{ "keyCode": "ScrollWheel", "functionType": "ScrollWheel", "value": "Volume", "hid": 1922, "translate": "ScrollWheel", "code": "ScrollWheel" },
{ "keyCode": "Custom_Fnkey", "functionType": "Custom_Fnkey", "value": "FN", "hid": "0x781", "translate": "FN", "code": "Custom_Fnkey" },
{ "keyCode": "0", "functionType": "Singlekey", "value": "Left Click", "hid": 0xB0, "hid_ModelO:": 0x01, "translate": "Left Click", "code": "0" },
{ "keyCode": "1", "functionType": "Singlekey", "value": "Scroll Click", "hid": 0xB2, "hid_ModelO:": 0x03, "translate": "Scroll Click", "code": "1" },
{ "keyCode": "2", "functionType": "Singlekey", "value": "Right Click", "hid": 0xB1, "hid_ModelO:": 0x02, "translate": "Right Click", "code": "2" },
{ "keyCode": "3", "functionType": "Singlekey", "value": "Back Key", "hid": 0xB3, "hid_ModelO": 0x02, "translate": "Back Key", "code": "3" },
{ "keyCode": "4", "functionType": "Singlekey", "value": "Forward Key", "hid": 0xB4, "hid_ModelO": 0x02, "translate": "Forward Key", "code": "4" },
{ "keyCode": "65", "functionType": "Singlekey", "value": "A", "hid": 0x04, "translate": "A", "code": "KeyA" },
{ "keyCode": "66", "functionType": "Singlekey", "value": "B", "hid": 0x05, "translate": "B", "code": "KeyB" },
{ "keyCode": "67", "functionType": "Singlekey", "value": "C", "hid": 0x06, "translate": "C", "code": "KeyC" },
{ "keyCode": "68", "functionType": "Singlekey", "value": "D", "hid": 0x07, "translate": "D", "code": "KeyD" },
{ "keyCode": "69", "functionType": "Singlekey", "value": "E", "hid": 0x08, "translate": "E", "code": "KeyE" },
{ "keyCode": "70", "functionType": "Singlekey", "value": "F", "hid": 0x09, "translate": "F", "code": "KeyF" },
{ "keyCode": "71", "functionType": "Singlekey", "value": "G", "hid": 0x0A, "translate": "G", "code": "KeyG" },
{ "keyCode": "72", "functionType": "Singlekey", "value": "H", "hid": 0x0B, "translate": "H", "code": "KeyH" },
{ "keyCode": "73", "functionType": "Singlekey", "value": "I", "hid": 0x0C, "translate": "I", "code": "KeyI" },
{ "keyCode": "74", "functionType": "Singlekey", "value": "J", "hid": 0x0D, "translate": "J", "code": "KeyJ" },
{ "keyCode": "75", "functionType": "Singlekey", "value": "K", "hid": 0x0E, "translate": "K", "code": "KeyK" },
{ "keyCode": "76", "functionType": "Singlekey", "value": "L", "hid": 0x0F, "translate": "L", "code": "KeyL" },
{ "keyCode": "77", "functionType": "Singlekey", "value": "M", "hid": 0x10, "translate": "M", "code": "KeyM" },
{ "keyCode": "78", "functionType": "Singlekey", "value": "N", "hid": 0x11, "translate": "N", "code": "KeyN" },
{ "keyCode": "79", "functionType": "Singlekey", "value": "O", "hid": 0x12, "translate": "O", "code": "KeyO" },
{ "keyCode": "80", "functionType": "Singlekey", "value": "P", "hid": 0x13, "translate": "P", "code": "KeyP" },
{ "keyCode": "81", "functionType": "Singlekey", "value": "Q", "hid": 0x14, "translate": "Q", "code": "KeyQ" },
{ "keyCode": "82", "functionType": "Singlekey", "value": "R", "hid": 0x15, "translate": "R", "code": "KeyR" },
{ "keyCode": "83", "functionType": "Singlekey", "value": "S", "hid": 0x16, "translate": "S", "code": "KeyS" },
{ "keyCode": "84", "functionType": "Singlekey", "value": "T", "hid": 0x17, "translate": "T", "code": "KeyT" },
{ "keyCode": "85", "functionType": "Singlekey", "value": "U", "hid": 0x18, "translate": "U", "code": "KeyU" },
{ "keyCode": "86", "functionType": "Singlekey", "value": "V", "hid": 0x19, "translate": "V", "code": "KeyV" },
{ "keyCode": "87", "functionType": "Singlekey", "value": "W", "hid": 0x1A, "translate": "W", "code": "KeyW" },
{ "keyCode": "88", "functionType": "Singlekey", "value": "X", "hid": 0x1B, "translate": "X", "code": "KeyX" },
{ "keyCode": "89", "functionType": "Singlekey", "value": "Y", "hid": 0x1C, "translate": "Y", "code": "KeyY" },
{ "keyCode": "90", "functionType": "Singlekey", "value": "Z", "hid": 0x1D, "translate": "Z", "code": "KeyZ" },
{ "keyCode": "48", "functionType": "Singlekey", "value": "0", "hid": 0x27, "translate": "0", "code": "Digit0" },
{ "keyCode": "49", "functionType": "Singlekey", "value": "1", "hid": 0x1E, "translate": "1", "code": "Digit1" },
{ "keyCode": "50", "functionType": "Singlekey", "value": "2", "hid": 0x1F, "translate": "2", "code": "Digit2" },
{ "keyCode": "51", "functionType": "Singlekey", "value": "3", "hid": 0x20, "translate": "3", "code": "Digit3" },
{ "keyCode": "52", "functionType": "Singlekey", "value": "4", "hid": 0x21, "translate": "4", "code": "Digit4" },
{ "keyCode": "53", "functionType": "Singlekey", "value": "5", "hid": 0x22, "translate": "5", "code": "Digit5" },
{ "keyCode": "54", "functionType": "Singlekey", "value": "6", "hid": 0x23, "translate": "6", "code": "Digit6" },
{ "keyCode": "55", "functionType": "Singlekey", "value": "7", "hid": 0x24, "translate": "7", "code": "Digit7" },
{ "keyCode": "56", "functionType": "Singlekey", "value": "8", "hid": 0x25, "translate": "8", "code": "Digit8" },
{ "keyCode": "57", "functionType": "Singlekey", "value": "9", "hid": 0x26, "translate": "9", "code": "Digit9" },
{ "keyCode": "8", "functionType": "Singlekey", "value": "Backspace", "hid": 42, "translate": "Backspace", "code": "Backspace" },
{ "keyCode": "9", "functionType": "Singlekey", "value": "Tab", "hid": 43, "translate": "Tab", "code": "Tab" },
{ "keyCode": "144", "functionType": "Singlekey", "value": "Num Lock", "hid": 83, "translate": "Num Lock", "code": "NumLock" },
{ "keyCode": "13", "functionType": "Singlekey", "value": "Enter", "hid": 40, "translate": "Enter", "code": "Enter" },
{ "keyCode": "16", "functionType": "Singlekey", "value": "Shift", "hid": 225, "translate": "Shift", "code": "ShiftRight" },
{ "keyCode": "16", "functionType": "Singlekey", "value": "Shift", "hid": 225, "translate": "Shift", "code": "ShiftLeft" },
{ "keyCode": "17", "functionType": "Singlekey", "value": "Ctrl", "hid": 224, "translate": "Ctrl", "code": "ControlLeft" },
{ "keyCode": "17", "functionType": "Singlekey", "value": "Ctrl", "hid": 224, "translate": "Ctrl", "code": "ControlRight" },
{ "keyCode": "18", "functionType": "Singlekey", "value": "Alt", "hid": 226, "translate": "Alt", "code": "AltRight" },
{ "keyCode": "18", "functionType": "Singlekey", "value": "Alt", "hid": 226, "translate": "Alt", "code": "AltLeft" },
{ "keyCode": "19", "functionType": "Singlekey", "value": "Break", "hid": 72, "translate": "Break", "code": "Pause" },
{ "keyCode": "20", "functionType": "Singlekey", "value": "CapsLock", "hid": 57, "translate": "CapsLock", "code": "CapsLock" },
{ "keyCode": "27", "functionType": "Singlekey", "value": "Esc", "hid": 41, "translate": "Esc", "code": "Escape" },
{ "keyCode": "32", "functionType": "Singlekey", "value": "Space", "hid": 44, "translate": "Space", "code": "Space" },
{ "keyCode": "33", "functionType": "Singlekey", "value": "PageUp", "hid": 75, "translate": "PageUp", "code": "PageUp" },
{ "keyCode": "34", "functionType": "Singlekey", "value": "PageDown", "hid": 78, "translate": "PageDown", "code": "PageDown" },
{ "keyCode": "35", "functionType": "Singlekey", "value": "End", "hid": 77, "translate": "End", "code": "End" },
{ "keyCode": "36", "functionType": "Singlekey", "value": "Home", "hid": 74, "translate": "Home", "code": "Home" },
{ "keyCode": "37", "functionType": "Singlekey", "value": "Left", "hid": 80, "translate": "Left", "code": "ArrowLeft" },
{ "keyCode": "38", "functionType": "Singlekey", "value": "Up", "hid": 82, "translate": "Up", "code": "ArrowUp" },
{ "keyCode": "39", "functionType": "Singlekey", "value": "Right", "hid": 79, "translate": "Right", "code": "ArrowRight" },
{ "keyCode": "40", "functionType": "Singlekey", "value": "Down", "hid": 81, "translate": "Down", "code": "ArrowDown" },
{ "keyCode": "44", "functionType": "Singlekey", "value": "PrintScreen", "hid": "0x46", "translate": "PrintScreen", "code": "PrintScreen" },
{ "keyCode": "45", "functionType": "Singlekey", "value": "Insert", "hid": 73, "translate": "Insert", "code": "Insert" },
{ "keyCode": "46", "functionType": "Singlekey", "value": "Delete", "hid": 76, "translate": "Delete", "code": "Delete" },
{ "keyCode": "91", "functionType": "Singlekey", "value": "Left Win", "hid": 227, "translate": "Left Win", "code": "MetaLeft" },
{ "keyCode": "92", "functionType": "Singlekey", "value": "Right Win", "hid": 231, "Modifier": 0x80, "translate": "Right Win", "code": "MetaRight" },
{ "keyCode": "93", "functionType": "Singlekey", "value": "Menu", "hid": 101, "translate": "Menu", "code": "ContextMenu" },
{ "keyCode": "96", "functionType": "Singlekey", "value": "0", "hid": 0x62, "translate": "Numpad0", "code": "Numpad0" },
{ "keyCode": "97", "functionType": "Singlekey", "value": "1", "hid": 0x59, "translate": "Numpad1", "code": "Numpad1" },
{ "keyCode": "98", "functionType": "Singlekey", "value": "2", "hid": 0x5a, "translate": "Numpad2", "code": "Numpad2" },
{ "keyCode": "99", "functionType": "Singlekey", "value": "3", "hid": 0x5b, "translate": "Numpad3", "code": "Numpad3" },
{ "keyCode": "100", "functionType": "Singlekey", "value": "4", "hid": 0x5c, "translate": "Numpad4", "code": "Numpad4" },
{ "keyCode": "101", "functionType": "Singlekey", "value": "5", "hid": 0x5d, "translate": "Numpad5", "code": "Numpad5" },
{ "keyCode": "102", "functionType": "Singlekey", "value": "6", "hid": 0x5e, "translate": "Numpad6", "code": "Numpad6" },
{ "keyCode": "103", "functionType": "Singlekey", "value": "7", "hid": 0x5f, "translate": "Numpad7", "code": "Numpad7" },
{ "keyCode": "104", "functionType": "Singlekey", "value": "8", "hid": 0x60, "translate": "Numpad8", "code": "Numpad8" },
{ "keyCode": "105", "functionType": "Singlekey", "value": "9", "hid": 0x61, "translate": "Numpad9", "code": "Numpad9" },
{ "keyCode": "13", "functionType": "Singlekey", "value": "Enter", "hid": 0x58, "translate": "NumpadEnter", "code": "NumpadEnter" },
{ "keyCode": "106", "functionType": "Singlekey", "value": "*", "hid": 85, "translate": "*", "code": "NumpadMultiply" },
{ "keyCode": "107", "functionType": "Singlekey", "value": "+", "hid": 87, "translate": "+", "code": "NumpadAdd" },
{ "keyCode": "109", "functionType": "Singlekey", "value": "-", "hid": 86, "translate": "-", "code": "NumpadSubtract" },
{ "keyCode": "110", "functionType": "Singlekey", "value": ".", "hid": 0x63, "translate": ".", "code": "NumpadDecimal" },
{ "keyCode": "111", "functionType": "Singlekey", "value": "/", "hid": 84, "translate": "/", "code": "NumpadDivide" },
{ "keyCode": "112", "functionType": "Singlekey", "value": "F1", "hid": 0x3A, "translate": "F1", "code": "F1" },
{ "keyCode": "113", "functionType": "Singlekey", "value": "F2", "hid": 0x3B, "translate": "F2", "code": "F2" },
{ "keyCode": "114", "functionType": "Singlekey", "value": "F3", "hid": 0x3C, "translate": "F3", "code": "F3" },
{ "keyCode": "115", "functionType": "Singlekey", "value": "F4", "hid": 0x3D, "translate": "F4", "code": "F4" },
{ "keyCode": "116", "functionType": "Singlekey", "value": "F5", "hid": 0x3E, "translate": "F5", "code": "F5" },
{ "keyCode": "117", "functionType": "Singlekey", "value": "F6", "hid": 0x3F, "translate": "F6", "code": "F6" },
{ "keyCode": "118", "functionType": "Singlekey", "value": "F7", "hid": 0x40, "translate": "F7", "code": "F7" },
{ "keyCode": "119", "functionType": "Singlekey", "value": "F8", "hid": 0x41, "translate": "F8", "code": "F8" },
{ "keyCode": "120", "functionType": "Singlekey", "value": "F9", "hid": 0x42, "translate": "F9", "code": "F9" },
{ "keyCode": "121", "functionType": "Singlekey", "value": "F10", "hid": 0x43, "translate": "F10", "code": "F10" },
{ "keyCode": "122", "functionType": "Singlekey", "value": "F11", "hid": 0x44, "translate": "F11", "code": "F11" },
{ "keyCode": "123", "functionType": "Singlekey", "value": "F12", "hid": 0x45, "translate": "F12", "code": "F12" },
{ "keyCode": "145", "functionType": "Singlekey", "value": "Scroll Lock", "hid": 71, "translate": "Scroll Lock", "code": "ScrollLock" },
{ "keyCode": "186", "functionType": "Singlekey", "value": ";", "hid": 51, "translate": ";", "code": "Semicolon" },
{ "keyCode": "187", "functionType": "Singlekey", "value": "=", "hid": 46, "translate": "=", "code": "Equal" },
{ "keyCode": "188", "functionType": "Singlekey", "value": ",", "hid": 54, "translate": ",", "code": "Comma" },
{ "keyCode": "189", "functionType": "Singlekey", "value": "-", "hid": 45, "translate": "-", "code": "Minus" },
{ "keyCode": "190", "functionType": "Singlekey", "value": "dot", "hid": 55, "translate": "dot", "code": "Period" },
{ "keyCode": "191", "functionType": "Singlekey", "value": "/", "hid": 56, "translate": "/", "code": "Slash" },
{ "keyCode": "192", "functionType": "Singlekey", "value": "~", "hid": 53, "translate": "~", "code": "Backquote" },
{ "keyCode": "219", "functionType": "Singlekey", "value": "[", "hid": 47, "translate": "[", "code": "BracketLeft" },
{ "keyCode": "220", "functionType": "Singlekey", "value": "|", "hid": 49, "translate": "|", "code": "Backslash" },
{ "keyCode": "226", "functionType": "Singlekey", "value": "\\", "hid": 49, "translate": "IntlBackslash", "code": "IntlBackslash" },
{ "keyCode": "221", "functionType": "Singlekey", "value": "]", "hid": 48, "translate": "]", "code": "BracketRight" },
{ "keyCode": "222", "functionType": "Singlekey", "value": "'", "hid": 52, "translate": "'", "code": "Quote" }]

export const i18n_Localization ={"connectionLimit":{"EN":[true,true,true,true,true,true,false,false],"CH":[false,false,true,true,true,false,true,true],"CN":[false,false,true,true,true,false,true,true]},"SLEEP":{"EN":"sleep","CH":"休眠","CN":"休眠"},"WINKEYSETTING":{"EN":"win key setting","CH":"Win鍵設定","CN":"Win键设定"},"ARROWKEYSWITCH":{"EN":"arrow key switch","CH":"方向切換","CN":"方向切换"},"MACROTYPE":{"EN":"Macro type","CH":"宏類別","CN":"宏类别"},"MACRONAME":{"EN":"Macro name","CH":"宏名稱","CN":"宏名称"},"MACRO":{"EN":"Macro","CH":"宏檔案","CN":"宏档案"},"DELAYMODE":{"EN":"Delay mode","CH":"延遲模式","CN":"延迟模式"},"DELAYRECORD":{"EN":"Delay record","CH":"紀錄延遲","CN":"纪录延迟"},"FIVEMINDELAY":{"EN":"5ms min delay","CH":"最低延遲5ms","CN":"最低延迟5ms"},"MSDELAY":{"EN":"Ms delay","CH":"ms延遲","CN":"ms延迟"},"RELEASETOSTOP":{"EN":"Release to stop","CH":"鬆開停止","CN":"松开停止"},"PRESSAGAINTOSTOP":{"EN":"Press again to stop","CH":"再次按下停止","CN":"再次按下停止"},"TIMESTOSTOP":{"EN":"Times to stop","CH":"次後停止","CN":"次后停止"},"NO_":{"EN":"No_","CH":"編號","CN":"编号"},"NAME":{"EN":"Name","CH":"名稱","CN":"名称"},"MS100":{"EN":"100ms","CH":"百毫秒","CN":"百毫秒"},"EFFECT":{"EN":"Effect","CH":"效果","CN":"效果"},"COLORSETTING":{"EN":"Color Set","CH":"顏色配置","CN":"颜色配置"},"LIGHTINGSPEED":{"EN":"Lightingspeed","CH":"顏色速度","CN":"颜色速度"},"DEFAULT":{"EN":"Default","CH":"預設","CN":"预设"},"SETTING":{"EN":"Setting","CH":"設置","CN":"设置"},"LANGUAGES":{"EN":"Languages","CH":"語言","CN":"语言"},"SAVE":{"EN":"Save","CH":"保存","CN":"保存"},"CANCEL":{"EN":"Cancel","CH":"取消","CN":"取消"},"VERSION":{"EN":"Version","CH":"版本","CN":"版本"},"UPDATE":{"EN":"Update","CH":"更新","CN":"更新"},"AUTOSTART":{"EN":"Run Software When Windows Starts","CH":"開機自動啟動","CN":"开机自动启动"},"FactoryReset":{"EN":"DEFAULT","CH":"恢復原廠設置","CN":"恢复原厂设置"},"HASNEWVERSION":{"EN":"New Updates","CH":"有新版本","CN":"有新版本"},"CONFIGURATION":{"EN":"Setting","CH":"配置","CN":"配置"},"LIGHTINGSETTING":{"EN":"Lighting Setting","CH":"顏色設置","CN":"颜色设置"},"MACROSETTINGS":{"EN":"Macro Setting","CH":"宏設置","CN":"宏设置"},"KEYBOARDSETTINGS":{"EN":"Keyboard Setting","CH":"按鍵設置","CN":"按键设置"},"RELATEDPROGRAM":{"EN":"Related Program","CH":"關聯程序","CN":"关联程序"},"CSUTOMEDIT":{"EN":"Edit","CH":"高級編輯","CN":"高级编辑"},"DEVICE":{"EN":"Device","CH":"添加設備","CN":"添加设备"},"CREATE":{"EN":"Create","CH":"新增","CN":"新增"},"DELETE":{"EN":"Delete","CH":"刪除","CN":"删除"},"EDIT":{"EN":"Edit","CH":"編輯","CN":"编辑"},"COPY":{"EN":"Copy","CH":"複製","CN":"复制"},"EXPORT":{"EN":"Export","CH":"匯出","CN":"汇出"},"IMPORT":{"EN":"Import","CH":"匯入","CN":"汇入"},"MOVEUP":{"EN":"Moveup","CH":"上移","CN":"上移"},"MOVEDOWN":{"EN":"Movedown","CH":"下移","CN":"下移"},"RECORDANDSTOPMACRO":{"EN":"Start/Stop","CH":"錄製/停止","CN":"录制/停止"},"HARDWARECONFIGURATION":{"EN":"Hardware","CH":"硬體配置","CN":"硬体配置"},"FUNCTION":{"EN":"Function","CH":"基礎功能","CN":"基础功能"},"NUM":{"EN":"Num","CH":"數字鍵區","CN":"数字键区"},"MEDIA":{"EN":"Media","CH":"多媒體","CN":"多媒体"},"SYSTEM":{"EN":"System","CH":"系統網路","CN":"系统网络"},"MOUSE":{"EN":"Mouse","CH":"滑鼠","CN":"鼠标"},"DISABLE":{"EN":"Disable","CH":"禁用","CN":"禁用"},"LAYER":{"EN":"Layer","CH":"層順時開關","CN":"层顺时开关"},"COMPLEX":{"EN":"Complex","CH":"組合鍵","CN":"组合键"},"MEDIAPLAYER":{"EN":"Mediaplayer","CH":"媒體播放器","CN":"媒体播放器"},"PLAYPAUSE":{"EN":"Play/pause","CH":"播放/暫停","CN":"播放/暂停"},"PREVIOUS":{"EN":"Previous","CH":"上一曲","CN":"上一曲"},"STOP":{"EN":"Stop","CH":"停止","CN":"停止"},"NEXT":{"EN":"Next","CH":"下一曲","CN":"下一曲"},"VOLUMEUP":{"EN":"Volumeup","CH":"音量加","CN":"音量加"},"VOLUMEDOWN":{"EN":"Volumedown","CH":"音量減","CN":"音量减"},"MUTE":{"EN":"Mute","CH":"靜音","CN":"静音"},"PAGEBACK":{"EN":"Pageback","CH":"瀏覽器後退","CN":"浏览器后退"},"PAGEFORWARD":{"EN":"Pageforward","CH":"瀏覽器前進","CN":"浏览器前进"},"REFRESHPAGE":{"EN":"Refreshpage","CH":"瀏覽器刷新","CN":"浏览器刷新"},"BROWSERCOLLECT":{"EN":"Collectpage","CH":"瀏覽器收藏","CN":"浏览器收藏"},"HOMEPAGE":{"EN":"Homepage","CH":"瀏覽器主頁","CN":"浏览器主页"},"EMAIL":{"EN":"Email","CH":"Email","CN":"Email"},"MYCOMPUTER":{"EN":"Mycomputer","CH":"我的電腦","CN":"我的电脑"},"PASTE":{"EN":"Paste","CH":"黏貼","CN":"黏贴"},"LEFTCLICK":{"EN":"Leftclick","CH":"單擊左建","CN":"单击左建"},"RIGHTCLICK":{"EN":"Rightclick","CH":"單擊右鍵","CN":"单击右键"},"SCROLLCLICK":{"EN":"Scrollclick","CH":"單擊滾輪","CN":"单击滚轮"},"BACK":{"EN":"Back","CH":"後退","CN":"后退"},"FORWARD":{"EN":"Forward","CH":"前進","CN":"前进"},"DISABLEALL":{"EN":"Disableall","CH":"禁用全部","CN":"禁用全部"},"UNDISABLE":{"EN":"Un-disable","CH":"取消禁用","CN":"取消禁用"},"DISABLENUMKEYS":{"EN":"Numkeys","CH":"禁用數字鍵","CN":"禁用数字键"},"DISABLELETTERS":{"EN":"Letters","CH":"禁用字母","CN":"禁用字母"},"DISABLESYMBOL":{"EN":"Symbol","CH":"禁用符號","CN":"禁用符号"},"DISABLECONTROLKEYS":{"EN":"Controlkeys","CH":"禁用控制鍵","CN":"禁用控制键"},"COMBINATIONKEY":{"EN":"Combinationkey","CH":"組合鍵","CN":"组合键"},"USE":{"EN":"Use","CH":"使用","CN":"使用"},"KEY":{"EN":"Key:","CH":"設定按鍵","CN":"设定按键"},"LIGHT":{"EN":"Light:","CH":"燈光設置","CN":"灯光设置"},"MESSAGE":{"EN":"Warning: The light effect has reached the limit of 11 groups.","CH":"警告:燈效已達上限11組請刪除後設定","CN":"警告:灯效已达上限11组请删除后设定"},"Apply":{"EN":"Apply","CH":"確定","CN":"确定"},"HARDWARE":{"EN":"Hardware troubleshoot","CH":"硬體檢測","CN":"硬体检测"},"GEEKCIRCLE":{"EN":"Kemove forum","CH":"極客圈","CN":"极客圈"},"COLORS":{"EN":"Colors:","CH":"插色數量:","CN":"插色数量:"},"SELECT":{"EN":"Select","CH":"框選","CN":"框选"},"CENTERTHEEFFECT":{"EN":"ORIGIN","CH":"起始點","CN":"起始點"},"OPACITY":{"EN":"Opacity","CH":"不透明度","CN":"不透明度"},"SPEED":{"EN":"Speed","CH":"速度","CN":"速度"},"BANDWIDTH":{"EN":"Bandwidth","CH":"帶寬","CN":"带宽"},"ANGLE":{"EN":"Angle","CH":"角度","CN":"角度"},"BUMP":{"EN":"Bump","CH":"回彈","CN":"回弹"},"AMPLITUDE":{"EN":"Amplitude","CH":"振幅","CN":"振幅"},"SEPARATE":{"EN":"Separate","CH":"分離","CN":"分离"},"GRADIENT":{"EN":"Gradient","CH":"梯度","CN":"梯度"},"DIRECTION":{"EN":"Direction","CH":"方向","CN":"方向"},"SOFT":{"EN":"Soft","CH":"柔邊","CN":"柔边"},"FIXED":{"EN":"Fixed","CH":"固定","CN":"固定"},"BIDIRECTIONAL":{"EN":"Bidirectional","CH":"雙向的","CN":"双向的"},"GAP":{"EN":"Gap","CH":"間隙","CN":"间隙"},"FIRE":{"EN":"Fire","CH":"火焰","CN":"火焰"},"RANDOMSPEED":{"EN":"Randomspeed","CH":"隨機速度","CN":"随机速度"},"TIME":{"EN":"Time","CH":"時間","CN":"时间"},"RADIUS":{"EN":"Radius","CH":"半徑","CN":"半径"},"NUMBER":{"EN":"Number","CH":"數量","CN":"数量"},"LED_MODE_NAME":{"EN":["Wave","Nexus","Spiral","Cycle","LinearWave","Ripple","Breathing","Rain","Fire","Trigger","AudioCap"],"CH":["波浪","撞擊","螺旋","循環","觸發","漣漪","呼吸","下雨","火焰","點亮","音樂"],"CN":["波浪","撞击","螺旋","循环","触发","涟漪","呼吸","下雨","火焰","点亮","音乐"]},"i18Select":{"EN":["EN","CH","CN"],"CH":["英文","繁體","簡體"],"CN":["英文","繁体","简体"]},"Sync Device":{"EN":"Sync Device","CH":"同步裝置","CN":"同步装置"},"Built-ineffects":{"EN":"Built-ineffects","CH":"內建燈效","CN":"內建灯效"},"Custom Effect":{"EN":"Custom Effect","CH":"高級燈效","CN":"高级灯效"},"Wave":{"EN":"Wave","CH":"波浪","CN":"波浪"},"Breath":{"EN":"Breath","CH":"呼吸","CN":"呼吸"},"Cycle":{"EN":"Cycle","CH":"循環","CN":"循环"},"Starlight":{"EN":"Starlight","CH":"繁星","CN":"繁星"},"Encounter":{"EN":"Encounter","CH":"邂逅","CN":"邂逅"},"Rain":{"EN":"Rain","CH":"下雨","CN":"下雨"},"Pulse":{"EN":"Pulse","CH":"脈衝","CN":"脉冲"},"Cross":{"EN":"Cross","CH":"十字","CN":"十字"},"Trigger":{"EN":"Trigger","CH":"點亮","CN":"点亮"},"Ripple":{"EN":"Ripple","CH":"漣漪","CN":"涟漪"},"Blossom":{"EN":"Blossom","CH":"綻放","CN":"绽放"},"Game_Mode":{"EN":"Game Mode","CH":"遊戲模式","CN":"游戏模式"},"Lighting":{"EN":"Lighting","CH":"單色","CN":"单色"},"Neon_stream":{"EN":"Neon stream","CH":"随波逐流","CN":"随波逐流"},"Rainbow_wheel":{"EN":"Rainbow wheel","CH":"彩虹轮盘","CN":"彩虹轮盘"},"Adorn":{"EN":"Adorn","CH":"百花争艳","CN":"百花争艳"},"Stars_twinkle":{"EN":"Stars twinkle","CH":"繁星点点","CN":"繁星点点"},"Shadow_disappear":{"EN":"Shadow disappear","CH":"踏雪无痕","CN":"踏雪无痕"},"Retro_snake":{"EN":"Retro snake","CH":"川流不息","CN":"川流不息"},"ColorLoop":{"EN":"ColorLoop","CH":"光谱循环","CN":"光谱循环"},"Respire":{"EN":"Respire","CH":"呼吸模式","CN":"呼吸模式"},"Fixed_on":{"EN":"Fixed_on","CH":"常亮模式","CN":"常亮模式"},"Ripples_shining":{"EN":"Ripples_shining","CH":"涟漪扩散","CN":"涟漪扩散"},"Reaction":{"EN":"Reaction","CH":"如影随形","CN":"如影随形"},"Flash_away":{"EN":"Flash_away","CH":"一触即发","CN":"一触即发"},"Sine_wave":{"EN":"Sine_wave","CH":"正弦光波","CN":"正弦光波"},"Raindrops":{"EN":"Raindrops","CH":"雨中漫步","CN":"雨中漫步"},"MAD_CATZ":{"EN":"MAD CATZ","CH":"MAD CATZ","CN":"MAD CATZ"},"BRIGHTNESS":{"EN":"Brightness","CH":"亮度","CN":"亮度"},"MULTICOLOR":{"EN":"Multicolor","CH":"多色","CN":"多色"},"ConicBand":{"EN":"Nexus","CH":"撞擊","CN":"撞击"},"Spiral":{"EN":"Spiral","CH":"螺旋","CN":"螺旋"},"LinearWave":{"EN":"LinearWave","CH":"觸發","CN":"触发"},"Breathing":{"EN":"Breathing","CH":"呼吸","CN":"呼吸"},"Fire":{"EN":"Fire","CH":"火焰","CN":"火焰"},"AudioCap":{"EN":"AudioCap","CH":"音樂","CN":"音乐"},"SW_Version":{"EN":"SW_Version","CH":"軟體版本","CN":"软体版本"},"FW_Version":{"EN":"FW_Version","CH":"韌體版本","CN":"韧体版本"}}



export class SupportData {
}


